{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "es-ES",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "POWERBI\\DWHPOWERBI",
            "database": "DWH_CLP"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "powerbi\\dwhpowerbi;DWH_CLP",
          "Username": "serviciospowerbi",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "fact Costes_Real",
        "columns": [
          {
            "name": "CLV_Mandante",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Mandante",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Tipo de moneda para una sociedad PA",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Tipo de moneda para una sociedad PA",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Clase de operación",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Clase de operación",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Versión plan (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Versión plan (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Período/Año",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Período/Año",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Número para objetos PA (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Número para objetos PA (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Historial de modificación para objetos PA (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Historial de modificación para objetos PA (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Nº de documento del cálculo de resultados de prtd.individual",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Nº de documento del cálculo de resultados de prtd.individual",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Número de posición de la cuenta de resultados de PI",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Número de posición de la cuenta de resultados de PI",
            "isAvailableInMdx": false
          },
          {
            "name": "T/C de conversión de mon. de área de resultados -> mon. soc.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "T/C de conversión de mon. de área de resultados -> mon. soc.",
            "isAvailableInMdx": false
          },
          {
            "name": "T/C de conversión de mon. del área de resultados -> mon. gp.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "T/C de conversión de mon. del área de resultados -> mon. gp.",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste Producto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste Producto",
            "isAvailableInMdx": false
          },
          {
            "name": "Volumen de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Volumen de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Ingresos",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ingresos",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Ctd. imputación",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Ctd. imputación",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Precio Input",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Precio Input",
            "isAvailableInMdx": false
          },
          {
            "name": "Desviac.Estructura",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desviac.Estructura",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Ctd. a emplear",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Ctd. a emplear",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Restante input",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Restante input",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.precio imputac.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.precio imputac.",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Costes Fijos",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Costes Fijos",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappels",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappels",
            "isAvailableInMdx": false
          },
          {
            "name": "Descuentos ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Descuentos ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Descuento por pronto pago",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Descuento por pronto pago",
            "isAvailableInMdx": false
          },
          {
            "name": "Diferencia de precio",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Diferencia de precio",
            "isAvailableInMdx": false
          },
          {
            "name": "Comisión de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Comisión de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Precio estándar",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Precio estándar",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos generales de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos generales de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos generales de gestión",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos generales de gestión",
            "isAvailableInMdx": false
          },
          {
            "name": "Desviacion Restante",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desviacion Restante",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Rechazo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Rechazo",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra de troqueles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra de troqueles",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra de cliches",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra de cliches",
            "isAvailableInMdx": false
          },
          {
            "name": "Materias primas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Materias primas",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappels Compras",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappels Compras",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv. Precio Mixto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv. Precio Mixto",
            "isAvailableInMdx": false
          },
          {
            "name": "Estr. Administración",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estr. Administración",
            "isAvailableInMdx": false
          },
          {
            "name": "Logística Cargas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Logística Cargas",
            "isAvailableInMdx": false
          },
          {
            "name": "Crédito y Caución",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Crédito y Caución",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste vtas cogen.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste vtas cogen.",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Cogeneración",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Cogeneración",
            "isAvailableInMdx": false
          },
          {
            "name": "Estructura Comercial",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estructura Comercial",
            "isAvailableInMdx": false
          },
          {
            "name": "Chep Palet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Chep Palet",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Extraord.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Extraord.",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Financieros",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Financieros",
            "isAvailableInMdx": false
          },
          {
            "name": "Estructura General",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estructura General",
            "isAvailableInMdx": false
          },
          {
            "name": "Impuesto s/bº",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Impuesto s/bº",
            "isAvailableInMdx": false
          },
          {
            "name": "Ing. Extraordinarios",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ing. Extraordinarios",
            "isAvailableInMdx": false
          },
          {
            "name": "Ingresos Financieros",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ingresos Financieros",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste de Montaje",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste de Montaje",
            "isAvailableInMdx": false
          },
          {
            "name": "Canon Plaform",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Canon Plaform",
            "isAvailableInMdx": false
          },
          {
            "name": "Transporte Externo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Transporte Externo",
            "isAvailableInMdx": false
          },
          {
            "name": "Transporte Interno",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Transporte Interno",
            "isAvailableInMdx": false
          },
          {
            "name": "Cantidad en M2",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cantidad en M2",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappel en Pedido",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappel en Pedido",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra Utiles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra Utiles",
            "isAvailableInMdx": false
          },
          {
            "name": "Mapfre",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Mapfre",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Montadora",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Montadora",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos recorte",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos recorte",
            "isAvailableInMdx": false
          },
          {
            "name": "Dtos PP Compras",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Dtos PP Compras",
            "isAvailableInMdx": false
          },
          {
            "name": "Merma real",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Merma real",
            "isAvailableInMdx": false
          },
          {
            "name": "Merma teórica",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Merma teórica",
            "isAvailableInMdx": false
          },
          {
            "name": "C.Transp.Teórico",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "C.Transp.Teórico",
            "isAvailableInMdx": false
          },
          {
            "name": "Rec.Multsdad",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rec.Multsdad",
            "isAvailableInMdx": false
          },
          {
            "name": "Ineficiencias PP 1",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ineficiencias PP 1",
            "isAvailableInMdx": false
          },
          {
            "name": "Gast.dir.Cogenerac.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gast.dir.Cogenerac.",
            "isAvailableInMdx": false
          },
          {
            "name": "Margen Rentabilidad",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Margen Rentabilidad",
            "isAvailableInMdx": false
          },
          {
            "name": "Montaje",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Montaje",
            "isAvailableInMdx": false
          },
          {
            "name": "Papeles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Papeles",
            "isAvailableInMdx": false
          },
          {
            "name": "Pdtos Ondulados",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Pdtos Ondulados",
            "isAvailableInMdx": false
          },
          {
            "name": "Tintas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Tintas",
            "isAvailableInMdx": false
          },
          {
            "name": "Palets",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Palets",
            "isAvailableInMdx": false
          },
          {
            "name": "Aprov. Varios",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Aprov. Varios",
            "isAvailableInMdx": false
          },
          {
            "name": "Actividad Externa",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Actividad Externa",
            "isAvailableInMdx": false
          },
          {
            "name": "Costes Estructura",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Costes Estructura",
            "isAvailableInMdx": false
          },
          {
            "name": "MOD",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MOD",
            "isAvailableInMdx": false
          },
          {
            "name": "Horas Máquina",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Horas Máquina",
            "isAvailableInMdx": false
          },
          {
            "name": "Reserva 2",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Reserva 2",
            "isAvailableInMdx": false
          },
          {
            "name": "Reserva 3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Reserva 3",
            "isAvailableInMdx": false
          },
          {
            "name": "Peso bruto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Peso bruto",
            "isAvailableInMdx": false
          },
          {
            "name": "Condición Zuni",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Condición Zuni",
            "isAvailableInMdx": false
          },
          {
            "name": "Recargo Lidl",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Recargo Lidl",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Clientes",
            "dataType": "int64",
            "sourceColumn": "Id_Clientes"
          },
          {
            "name": "Id_Materiales",
            "dataType": "int64",
            "sourceColumn": "Id_Materiales"
          },
          {
            "name": "Id_Zona_Ventas",
            "dataType": "int64",
            "sourceColumn": "Id_Zona_Ventas"
          },
          {
            "name": "Id_Organizacion_Ventas",
            "dataType": "int64",
            "sourceColumn": "Id_Organizacion_Ventas"
          },
          {
            "name": "Id_Centros",
            "dataType": "int64",
            "sourceColumn": "Id_Centros"
          },
          {
            "name": "Id_Costes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Costes",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Sociedad",
            "dataType": "int64",
            "sourceColumn": "Id_Sociedad"
          },
          {
            "name": "Id_Sectores",
            "dataType": "int64",
            "sourceColumn": "Id_Sectores"
          },
          {
            "name": "Id_Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Id_Fecha"
          },
          {
            "name": "Cantidad en UD",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cantidad en UD",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Divisiones",
            "dataType": "int64",
            "sourceColumn": "Id_Divisiones"
          },
          {
            "name": "Id_Ramo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Ramo",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Coste_Real",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Coste_Real",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Atributos_Materiales_PROVISIONAL",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Atributos_Materiales_PROVISIONAL",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Atributos_Ramo_PROVISIONAL",
            "dataType": "int64",
            "sourceColumn": "Id_Atributos_Ramo_PROVISIONAL"
          },
          {
            "name": "Id_Personal 1",
            "dataType": "int64",
            "sourceColumn": "Id_Personal 1"
          },
          {
            "name": "Id_Personal 2",
            "dataType": "int64",
            "sourceColumn": "Id_Personal 2"
          },
          {
            "name": "Id_Proveedor 1",
            "dataType": "int64",
            "sourceColumn": "Id_Proveedor 1"
          },
          {
            "name": "Id_Proveedor 2",
            "dataType": "int64",
            "sourceColumn": "Id_Proveedor 2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    fact_Costes_Real = Source{[Schema=\"fact\",Item=\"Costes_Real\"]}[Data]",
                "in",
                "    fact_Costes_Real"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "€ Ingresos",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"B1\"",
              "        || 'dim Atributos_Costes'[Clase de factura] <= \"ZZZZ\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"ZGS1\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\",",
              "    'dim Material'[BK_MATERIAL] >= \"000000000000000000\"",
              "        && 'dim Material'[BK_MATERIAL] <= \"000000000000140045\"",
              "        ||'dim Material'[BK_MATERIAL] >= \"000000000000140047\"",
              "        &&'dim Material'[BK_MATERIAL] <= \"000000000000140139\"",
              "        ||'dim Material'[BK_MATERIAL] >= \"000000000000140141\"",
              "        &&'dim Material'[BK_MATERIAL] <= \"000000000000ZZZZZZ\"",
              ")",
              "          ",
              "        "
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Rec. Multsdad",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Rec.Multsdad] ),",
              "    ( 'dim Atributos_Costes'[Clase de factura] <= \"IV04\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"IV01\" )",
              "        || ( 'dim Atributos_Costes'[Clase de factura] <= \"ZV04\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"ZV01\" )",
              "        || ( 'dim Atributos_Costes'[Clase de factura] <= \"ZS4V\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"ZS1V\" )",
              "        || ( 'dim Atributos_Costes'[Clase de factura] <= \"IGS4\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"IGS1\" )",
              "        || ( 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        && 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\" ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ C.Transport. Teorico",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[C.Transp.Teórico] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"IV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZS1V\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZS4V\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IGS1\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IGS4\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Abono Mala Calidad",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Motivo de pedido (motivo de la operación)] = \"Z01\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Abono Roto montad.",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Clase de factura] >= \"ZG21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZG24\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Descuento Ventas",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Descuentos ventas] ),",
              "   'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        ||  'dim Atributos_Costes'[Clase de operación]= \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Dtos Rotos Montadora",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Merma real]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Precio Neto 5000",
            "expression": [
              "",
              "CALCULATE (",
              "    [** Precio Neto],",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\",",
              "    'dim Atributos_Costes'[División] = \"15\",",
              "    'dim Organizacion_Ventas'[BK_ORGVENT] = \"5000\"",
              ")",
              "/*",
              "CALCULATE (",
              "    SUM ('fact Costes_Real'[Precio estándar] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\",",
              "   'dim Atributos_Costes'[División] = \"15\",",
              "    'dim Organizacion_Ventas'[BK_ORGVENT] = \"5000\"",
              ")",
              "*/"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Precio Neto",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "   [** Precio Neto],",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"V\"",
              ")",
              "",
              "/*",
              "",
              "CALCULATE (",
              "    SUM ('fact Costes_Real'[Precio estándar]),",
              "   'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación]  = \"V\"",
              ")",
              "",
              "*/"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Ingresos Totales",
            "expression": " [€ Precio Neto 5000] + [€ Ingresos] + [€ C.Transport. Teorico] + [€ Rec. Multsdad] - [€ Abono Mala Calidad]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Rappels",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Rappels] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Venta Neta",
            "expression": " ( ([Ingresos Totales] - [€ Descuento Ventas]) + [€ Rappels] + [€ Abono Roto montad.] + [€ Abono Mala Calidad] ) - [€ Dtos Rotos Montadora]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Producto",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Coste Producto] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"IV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IVS1\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZS1V\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZS4V\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0000999999\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Precio Estandar",
            "expression": [
              "/*",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Precio estándar] ),",
              "     'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")",
              "*/",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Precio estándar] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0009999999\",",
              "    'dim Material'[BK_GrupoArticulos] >= \"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos] <= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >= \"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos] <= \"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Rec. Multsdad log",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Rec.Multsdad] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Pr. Estandar",
            "expression": "[€ Coste Producto] + [€ Precio Estandar] + [€ C.Transport. Teorico Multdad] + [€ Rec. Multsdad log]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Consumo Papeles",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Papeles] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"E\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0000099999\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Consumo Pdtos Ondulados",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Pdtos Ondulados] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0000099999\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Consumo Tintas",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Tintas] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Consumo Palets",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Palets] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Consumo Aprov. Varios",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Aprov. Varios] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Actividad Externa",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Actividad Externa] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Coste Horas maquina",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Horas Máquina] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Coste MOD",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[MOD]),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Coste Estructura",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Costes Estructura] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "* Coste Montaje",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Montaje]),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"S401\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\" ,",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Material'[BK_GrupoArticulos]>=\"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >=\"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos]<=\"ZVARIOS\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Desv. Product Costing",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ineficiencias PP 1]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Precio input",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Precio Input]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desviac. Estructura",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desviac.Estructura]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Ctd. a emplear",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Ctd. a emplear]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Restante input",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Restante input]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Precio imputac",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.precio imputac.]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Costes Fijos",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Costes Fijos]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Ctd imputacion",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Ctd. imputación]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desviacion Restante",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desviacion Restante]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Rechazo",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv.Rechazo]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Desv. Precio Mixto",
            "expression": [
              " ",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Desv. Precio Mixto]),",
              "    'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Desviacion Ordenes",
            "expression": " [** Desv. Precio input] + [** Desviac. Estructura] + [** Desv. Ctd. a emplear] + [** Desv. Restante input] +  [** Desv. Precio imputac] + [** Desv. Costes Fijos] + [** Desv. Ctd imputacion] + [** Desviacion Restante] + [** Desv. Rechazo] + [** Desv. Precio Mixto]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "ZTDOS51-- Margen Industrial",
            "expression": " ([Venta Neta] - [€ Precio Estandar])-[Desviacion Ordenes]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Comision de Ventas",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Comisión de ventas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Transporte Interno",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Transporte Interno] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Transporte Externo",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Transporte Externo] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Transporte Total",
            "expression": " [€ Coste Transporte Interno] + [€ Coste Transporte Externo]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Canon Unic",
            "expression": " [€ Canon Uniq] + [€ Canon Plaform]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Recargo Lidl",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Recargo Lidl] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Chep Palet",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Chep Palet] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Palets",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Reserva 2] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste de Montaje",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Coste de Montaje] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Seguro Caucion",
            "expression": " [€ Credito y Caucion] + [€ Mapfre]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Compra Troq/Cliches/Utiles",
            "expression": [
              "",
              "VAR _Troqueles =",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Compra de troqueles] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "        'dim Atributos_Costes'[Clase de factura] >= \"BV\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"F804\"",
              "            || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "            || 'dim Atributos_Costes'[Clase de factura] >= \"RE\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "    )",
              "VAR _Cliches =",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Compra de cliches] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "        'dim Atributos_Costes'[Clase de factura] >= \"BV\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"F804\"",
              "            || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "            || 'dim Atributos_Costes'[Clase de factura] >= \"RE\"",
              "            && 'dim Atributos_Costes'[Clase de factura] <= \"S204\"",
              "    )",
              "VAR _Utiles =",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Reserva 3] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "    )",
              "RETURN",
              "    _Troqueles + _Cliches + _Utiles"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Montadora",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Gastos Montadora] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Dir. Cogenerac.",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Gast.dir.Cogenerac.] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Recorte",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Gastos recorte] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"H\"",
              ")"
            ],
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "ZTDOS51-- Margen Contribucion",
            "expression": "( [ZTDOS51-- Margen Industrial] - ( [€ Comision de Ventas] + [€ Coste Transporte Interno] + [€ Coste Transporte Externo] + [€ Canon Plaform] + [€ Coste Chep Palet] + [€ Coste de Montaje] + [€ Credito y Caucion] + [€ Mapfre] + [€ Gastos Dir. Cogenerac.] + [€ Gastos Montadora] + [€ Coste Palets] + [€ Canon Uniq] + [€ Compra Troq/Cliches/Utiles] + [€ Coste Recargo Lidl] ) ) - [€ Gastos Recorte]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Canon Uniq",
            "expression": [
              "",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Condición Zuni] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "            || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "    )",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Canon Plaform",
            "expression": [
              "",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Canon Plaform] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "    )",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Credito y Caucion",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Crédito y Caución] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Mapfre",
            "expression": [
              "",
              "    CALCULATE (",
              "        SUM ( 'fact Costes_Real'[Mapfre] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "    )",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ingresos Fi/SD",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Material'[BK_MATERIAL] = \"000000000000140046\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Financieros",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Gastos Financieros] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Descuentos por pronto pago",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Descuento por pronto pago] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura Comercial",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Estructura Comercial] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Sociedad CO] = \"1000\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Logistica Carga/Mtto",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Logística Cargas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura Oficinas",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Estr. Administración] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura General",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Estructura General] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Cogeneracion",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Gastos Cogeneración] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "ZTDOS51-- Margen Operativo",
            "expression": " [ZTDOS51-- Margen Contribucion] - ( [€ Logistica Carga/Mtto]+ [€ Estructura Oficinas] + [€ Estructura General] + [€ Gastos Cogeneracion] + [€ Estructura Comercial])",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ing. Financieros",
            "expression": " [€ Ingresos Fi/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ingresos Ext/SD",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Material'[BK_MATERIAL] = \"000000000000140140\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "ZTDOS51-- Margen Final",
            "expression": " [ZTDOS51-- Margen Neto] + [€ Ingresos Ext/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ C.Transport. Teorico Multdad",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[C.Transp.Teórico] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\"",
              ")",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Cantidad M2 (Real)",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Cantidad en M2] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"0\",",
              "    'dim Clientes'[BK_CLIENTE]<>\"\"",
              ")",
              "",
              "/*  Se incluye el ultimo Filtro de Clientes ya que en los Informes de BO no estan tenido en cuenta los movimientos de M2 que no tienen cliente Asociado ",
              "     Por ejemplo en el mes de Enero de 2021 hay 119673 m2 no asociados a ningun cliente */"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Margen Final BO UNI",
            "expression": " [Margen Neto BO UNI] + [€ Ingresos Ext/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Neto BO UNI",
            "expression": " ( ( [Margen Operativo BO UNI] - [€ Gastos Financieros]) - [€ Descuentos por pronto pago]) + [€ Ingresos Fi/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Operativo BO UNI",
            "expression": " [Margen Contribucion BO UNI] - ( [€ Logistica Carga/Mtto]+ [€ Estructura Oficinas] + [€ Estructura General] + [€ Gastos Cogeneracion] + [€ Estructura Comercial])",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Contribucion BO UNI",
            "expression": [
              " ([Margen Industrial BO UNI]- ([€ Comision de Ventas]+[€ Coste Transporte Interno]+[€ Coste Transporte Externo]+[€ Canon Plaform]+[€ Coste Chep Palet]+",
              "[€ Coste de Montaje]+[€ Credito y Caucion]+[€ Mapfre]+[€ Compra Troq/Cliches/Utiles]+[€ Gastos Dir. Cogenerac.]+[€ Gastos Montadora]+ [Reserva 2 BO] + [Condicion Zuni  BO] + [€ Coste Recargo Lidl]))-[€ Gastos Recorte]"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Industrial BO UNI",
            "expression": " (((([Venta Neta BO]- [Pr. Estandar BO])- [Desv. Product Costing]) - [€ Coste Producto]) - [€ C.Transport. Teorico Multdad] ) - [€ Rec. Multsdad log]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "** Precio Neto",
            "expression": [
              " [€ Ingresos] - [€ Descuento Ventas] - [€ Mermas real]",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Mermas real",
            "expression": " SUM('fact Costes_Real'[Merma real])",
            "formatString": "#,0"
          },
          {
            "name": "M2 Real SPLY",
            "expression": " CALCULATE([Total Cantidad M2 (Real)],SAMEPERIODLASTYEAR('dim Fechas'[Fecha]))"
          },
          {
            "name": "Total Cantidad UD (Real)",
            "expression": [
              "/***** Opcion Inicial del Desarrollo ******/",
              "VAR _Opcion1 =",
              "    CALCULATE(",
              "        SUM( 'fact Costes_Real'[Volumen de ventas] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "        'dim Atributos_Costes'[Indicador plan/real] = \"0\",",
              "        'dim Clientes'[BK_CLIENTE] <> \"\"",
              "    )",
              "",
              "/***** Opcion Vetnas ZPLAN002B Indicada por Alberto Romero ******/",
              "VAR _Opcion2 =",
              "    CALCULATE(",
              "        SUM( 'fact Costes_Real'[Volumen de ventas] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\" ",
              "            || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "            || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "            || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "        'dim Atributos_Costes'[Indicador plan/real] = \"0\",",
              "        'dim Clientes'[BK_CLIENTE] <> \"\"",
              "    )",
              "RETURN",
              "    _Opcion2",
              "",
              "/*  Se incluye el ultimo Filtro de Clientes ya que en los Informes de BO no estan tenido en cuenta los movimientos de M2 que no tienen cliente Asociado ",
              "     Por ejemplo en el mes de Enero de 2021 hay 119673 m2 no asociados a ningun cliente */"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Margen Contribucion BO",
            "expression": [
              " ([Margen Industrial BO]- ([€ Comision de Ventas]+[€ Coste Transporte Interno]+[€ Coste Transporte Externo]+[€ Canon Plaform]+[€ Coste Chep Palet]+",
              "[€ Coste de Montaje]+[€ Credito y Caucion]+[€ Mapfre]+[€ Compra Troq/Cliches/Utiles]+[€ Gastos Dir. Cogenerac.]+[€ Gastos Montadora]+ [Reserva 2 BO] + [Condicion Zuni  BO] + [€ Coste Recargo Lidl]))-[€ Gastos Recorte]",
              "",
              "/*( [Margen Industrial] - ( [€ Comision de Ventas] + [€ Coste Transporte Interno] + [€ Coste Transporte Externo] + ",
              "[€ Canon Plaform] + [€ Coste Chep Palet] + [€ Coste de Montaje] + [€ Credito y Caucion] + [€ Mapfre] + [€ Gastos Dir. Cogenerac.] + ",
              "[€ Gastos Montadora] + [€ Coste Palets] + [€ Canon Uniq] + [€ Compra Troq/Cliches/Utiles] + [€ Coste Recargo Lidl] ) ) - [€ Gastos Recorte]*/"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Reserva 2 BO",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Reserva 2] ),",
              "    'fact Costes_Real'[CLV_Clase de operación] = \"F\"",
              "        || 'fact Costes_Real'[CLV_Clase de operación] = \"C\"",
              ")"
            ],
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Condicion Zuni  BO",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Real'[Condición Zuni] ),",
              "    'fact Costes_Real'[CLV_Clase de operación] = \"F\"",
              "        || 'fact Costes_Real'[CLV_Clase de operación] = \"C\"",
              ")"
            ]
          },
          {
            "name": "Margen Industrial BO",
            "expression": " (((([Venta Neta]- [Pr. Estandar])- [Desv. Product Costing]) - [€ Coste Producto]) - [€ C.Transport. Teorico Multdad] ) - [€ Rec. Multsdad log]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Operativo BO",
            "expression": " [Margen Contribucion BO] - ( [€ Logistica Carga/Mtto]+ [€ Estructura Oficinas] + [€ Estructura General] + [€ Gastos Cogeneracion] + [€ Estructura Comercial])",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Neto BO",
            "expression": " ( ( [Margen Operativo BO] - [€ Gastos Financieros]) - [€ Descuentos por pronto pago]) + [€ Ingresos Fi/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Final BO",
            "expression": " [Margen Neto BO] + [€ Ingresos Ext/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "% Margen Final BO",
            "expression": [
              " DIVIDE([Margen Final BO] , [Venta Neta] , BLANK())",
              "",
              "/*",
              "([Margen Final BO] / [Venta Neta])",
              "",
              "*/"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Venta Neta BO",
            "expression": " ( ([Ingresos Totales BO UNI] - [€ Descuento Ventas]) + [€ Rappels] + [€ Abono Roto montad.] + [€ Abono Mala Calidad] ) - [€ Dtos Rotos Montadora]",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Pr. Estandar BO",
            "expression": "[€ Coste Producto] + [€ Precio Estandar]",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Ingresos Totales BO UNI",
            "expression": " [€ Ingresos] + [€ C.Transport. Teorico] + [€ Rec. Multsdad] - [€ Abono Mala Calidad]"
          },
          {
            "name": "% Margen Final BO UNI",
            "expression": [
              " DIVIDE([Margen Final BO UNI] , [Venta Neta BO] , BLANK())",
              "/*",
              "([Margen Final BO UNI] / [Venta Neta BO])",
              "*/"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "% Pr. Estandar",
            "expression": " DIVIDE([Pr. Estandar],[Venta Neta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "% Desv. Ordenes",
            "expression": " DIVIDE([Desviacion Ordenes],[Venta Neta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "% Product Costing",
            "expression": " DIVIDE([Desv. Product Costing],[Venta Neta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "% Margen Industrial",
            "expression": " DIVIDE([ZTDOS51-- Margen Industrial],[Venta Neta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Total Clientes con Venta",
            "expression": [
              "",
              "",
              "VAR TableSum = SUMMARIZE('fact Costes_Real','fact Costes_Real'[Id_Clientes],\"Total Venta\",[Venta Neta])",
              "VAR ClientesVenta = FILTER(TableSum,[Total Venta]>0)",
              "VAR Opcion1 =CALCULATE(COUNTROWS(ClientesVenta))",
              "",
              "",
              "Return Opcion1"
            ]
          },
          {
            "name": "ZTDOS51-- Margen Neto",
            "expression": " ( ( [ZTDOS51-- Margen Operativo] - [€ Gastos Financieros]) - [€ Descuentos por pronto pago]) + [€ Ingresos Fi/SD]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "ZCTAREDOS2 -- % Margen Contribucion",
            "expression": "DIVIDE( [ZCTAREDOS2-- Margen Contribucion], [Venta Neta] )",
            "formatString": "#,##0.0 %"
          },
          {
            "name": "ZCTAREDOS2 -- % Margen Final",
            "expression": " DIVIDE([ZCTAREDOS2-- Margen Final],[Venta Neta])",
            "formatString": "#,##0.0 %"
          },
          {
            "name": "ZCTAREDOS2 -- % Margen Industrial",
            "expression": "DIVIDE( [ZCTAREDOS2-- Margen Industrial], [Venta Neta] )",
            "formatString": "#,##0.0 %"
          },
          {
            "name": "ZCTAREDOS2 -- % Margen Operativo",
            "expression": "DIVIDE( [ZCTAREDOS2-- Margen Operativo], [Venta Neta] )",
            "formatString": "#,##0.0 %"
          },
          {
            "name": "ZCTAREDOS2-- Margen Contribucion",
            "expression": [
              "( [ZCTAREDOS2-- Margen Industrial]",
              "    - ( [€ Comision de Ventas] + [€ Coste Transporte Interno]",
              "    + [€ Coste Transporte Externo]",
              "    + [€ Canon Plaform]",
              "    + [€ Canon Uniq]",
              "    + [€ Coste Chep Palet]",
              "    + [€ Coste de Montaje]",
              "    + [€ Credito y Caucion]",
              "    + [€ Compra Troq/Cliches/Utiles]",
              "    + [€ Mapfre]",
              "    + [€ Gastos Dir. Cogenerac.]",
              "    + [€ Gastos Montadora]",
              "    + [€ Coste Palets]",
              "    + [€ Coste Recargo Lidl] ) )",
              "    - [€ Gastos Recorte]"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "ZCTAREDOS2-- Margen Final",
            "expression": "[ZCTAREDOS2-- Margen Neto] + [€ Ingresos Ext/SD]",
            "formatString": "#,##0"
          },
          {
            "name": "ZCTAREDOS2-- Margen Industrial",
            "expression": "( [Venta Neta] - [€ Precio Estandar] ) - [Desv. Product Costing]",
            "formatString": "#,##0"
          },
          {
            "name": "ZCTAREDOS2-- Margen Neto",
            "expression": [
              "( ( [ZCTAREDOS2-- Margen Operativo] - [€ Gastos Financieros] )",
              "    - [€ Descuentos por pronto pago] )",
              "    + [€ Ingresos Fi/SD]"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "ZCTAREDOS2-- Margen Operativo",
            "expression": [
              "[ZCTAREDOS2-- Margen Contribucion]",
              "    - ( [€ Logistica Carga/Mtto] + [€ Estructura Oficinas]",
              "    + [€ Estructura General]",
              "    + [€ Gastos Cogeneracion]",
              "    + [€ Estructura Comercial] )"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "Total Real Vs Plan (m2)",
            "expression": "[Total Cantidad M2 (Real)]-[Total Cantidad M2 (Plan)]"
          },
          {
            "name": "Total Real vs Plan (€)",
            "expression": "[Ingresos Totales]-[Ingresos Totales Plan]"
          },
          {
            "name": "% Margen Final BO (No Hierar)",
            "expression": [
              "VAR _Margen = DIVIDE( [Margen Final BO], [Venta Neta], BLANK( ) )",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Margen",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Total Cantidad M2 (Real) (No Hierar)",
            "expression": [
              "VAR _Cantidad =",
              "    CALCULATE(",
              "        SUM( 'fact Costes_Real'[Cantidad en M2] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "        'dim Atributos_Costes'[Indicador plan/real] = \"0\",",
              "        'dim Clientes'[BK_CLIENTE] <> \"\"",
              "    )",
              "",
              "/*  Se incluye el ultimo Filtro de Clientes ya que en los Informes de BO no estan tenido en cuenta los movimientos de M2 que no tienen cliente Asociado ",
              "     Por ejemplo en el mes de Enero de 2021 hay 119673 m2 no asociados a ningun cliente */",
              "",
              "",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Cantidad",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Venta Neta (No Hierar)",
            "expression": [
              "VAR _Venta =",
              "    ( ( [Ingresos Totales] - [€ Descuento Ventas] ) + [€ Rappels] + [€ Abono Roto montad.] + [€ Abono Mala Calidad] )",
              "        - [€ Dtos Rotos Montadora]",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Venta",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Venta Neta Real vs Plan (€)",
            "expression": "[Venta Neta] - [Venta Neta Plan]"
          }
        ]
      },
      {
        "name": "dim Clientes",
        "columns": [
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_SPRAS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_SPRAS"
          },
          {
            "name": "BK_PAIS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PAIS"
          },
          {
            "name": "BK_PROVINCIA",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PROVINCIA"
          },
          {
            "name": "BK_CLIENTE",
            "dataType": "string",
            "sourceColumn": "BK_CLIENTE"
          },
          {
            "name": "BK_SECTOR",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_SECTOR"
          },
          {
            "name": "BK_RAMOINDUSTRIAL",
            "dataType": "string",
            "sourceColumn": "BK_RAMOINDUSTRIAL"
          },
          {
            "name": "Nombre",
            "dataType": "string",
            "sourceColumn": "Nombre"
          },
          {
            "name": "Poblacion",
            "dataType": "string",
            "sourceColumn": "Poblacion"
          },
          {
            "name": "Codig Postal",
            "dataType": "string",
            "sourceColumn": "Codig Postal"
          },
          {
            "name": "Provincia",
            "dataType": "string",
            "sourceColumn": "Provincia"
          },
          {
            "name": "Grupo de ctas.deudor",
            "dataType": "string",
            "sourceColumn": "Grupo de ctas.deudor"
          },
          {
            "name": "Clasificación de clientes",
            "dataType": "string",
            "sourceColumn": "Clasificación de clientes"
          },
          {
            "name": "Zona transporte entregas",
            "dataType": "string",
            "sourceColumn": "Zona transporte entregas"
          },
          {
            "name": "Sector",
            "dataType": "string",
            "sourceColumn": "Sector",
            "sortByColumn": "BK_SECTOR"
          },
          {
            "name": "Id_Clientes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Clientes"
          },
          {
            "name": "País",
            "dataType": "string",
            "sourceColumn": "País"
          },
          {
            "name": "Ramo Industrial",
            "dataType": "string",
            "sourceColumn": "Ramo Industrial"
          },
          {
            "name": "DescripcionNivel2",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel2"
          },
          {
            "name": "DescripcionNivel3",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel3"
          },
          {
            "name": "DescripcionNivel4",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel4"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Clientes = Source{[Schema=\"dim\",Item=\"Clientes\"]}[Data]",
                "in",
                "    dim_Clientes"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Ubicacion Clientes",
            "levels": [
              {
                "name": "País",
                "ordinal": 0,
                "column": "País"
              },
              {
                "name": "Provincia",
                "ordinal": 1,
                "column": "Provincia"
              }
            ]
          },
          {
            "name": "Jerarquia Ramo Cliente",
            "levels": [
              {
                "name": "Ramo Industrial",
                "ordinal": 3,
                "column": "Ramo Industrial"
              },
              {
                "name": "DescripcionNivel2",
                "ordinal": 2,
                "column": "DescripcionNivel2"
              },
              {
                "name": "DescripcionNivel4",
                "ordinal": 0,
                "column": "DescripcionNivel4"
              },
              {
                "name": "DescripcionNivel3",
                "ordinal": 1,
                "column": "DescripcionNivel3"
              }
            ]
          }
        ]
      },
      {
        "name": "ActualizacionDWH",
        "isHidden": true,
        "columns": [
          {
            "name": "ID_Ejecucion",
            "dataType": "int64",
            "sourceColumn": "ID_Ejecucion"
          },
          {
            "name": "Carpeta",
            "dataType": "string",
            "sourceColumn": "Carpeta"
          },
          {
            "name": "Proyecto",
            "dataType": "string",
            "sourceColumn": "Proyecto"
          },
          {
            "name": "Entorno",
            "dataType": "string",
            "sourceColumn": "Entorno"
          },
          {
            "name": "Usuario",
            "dataType": "string",
            "sourceColumn": "Usuario"
          },
          {
            "name": "Fecha Inicio",
            "dataType": "dateTime",
            "sourceColumn": "Fecha Inicio"
          },
          {
            "name": "Fecha Fin",
            "dataType": "dateTime",
            "sourceColumn": "Fecha Fin",
            "formatString": "dd/MM/yy HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"3082\" Group=\"GeneralLongDateTime\" FormatString=\"dd/MM/yy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Nombre Paquete SSIS",
            "dataType": "string",
            "sourceColumn": "Nombre Paquete SSIS"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dbo_ActualizacionDWH = Source{[Schema=\"dbo\",Item=\"ActualizacionDWH\"]}[Data]",
                "in",
                "    dbo_ActualizacionDWH"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actualizacion",
            "expression": " CALCULATE(MAX(ActualizacionDWH[Fecha Fin]),ActualizacionDWH[Nombre Paquete SSIS]=\"Orquestador Costes.dtsx\")",
            "formatString": "dd/MM/yyyy HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"3082\" Group=\"GeneralLongDateTime\" FormatString=\"dd/MM/yyyy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "dim Organizacion_Ventas",
        "columns": [
          {
            "name": "Id_Organizacion_Ventas",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Organizacion_Ventas"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_ORGVENT",
            "dataType": "string",
            "sourceColumn": "BK_ORGVENT"
          },
          {
            "name": "BK_SOCIEDAD",
            "dataType": "string",
            "sourceColumn": "BK_SOCIEDAD"
          },
          {
            "name": "BK_AREAVENTAS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_AREAVENTAS"
          },
          {
            "name": "Organizacion Ventas",
            "dataType": "string",
            "sourceColumn": "Organizacion Ventas"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Organizacion_Ventas = Source{[Schema=\"dim\",Item=\"Organizacion_Ventas\"]}[Data]",
                "in",
                "    dim_Organizacion_Ventas"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Zona_Ventas",
        "columns": [
          {
            "name": "ID Geografia",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID Geografia"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_SPRAS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_SPRAS"
          },
          {
            "name": "BK_PAIS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PAIS"
          },
          {
            "name": "BK_PROVINCIA",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PROVINCIA"
          },
          {
            "name": "BK_ZONAVENTAS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_ZONAVENTAS"
          },
          {
            "name": "Provincia",
            "dataType": "string",
            "sourceColumn": "Provincia"
          },
          {
            "name": "País",
            "dataType": "string",
            "sourceColumn": "País"
          },
          {
            "name": "Agrupacion Zonas",
            "dataType": "string",
            "sourceColumn": "Agrupacion Zonas"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Zona_Ventas = Source{[Schema=\"dim\",Item=\"Zona_Ventas\"]}[Data]",
                "in",
                "    dim_Zona_Ventas"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Ubicacion",
            "levels": [
              {
                "name": "País",
                "ordinal": 0,
                "column": "País"
              },
              {
                "name": "Provincia",
                "ordinal": 1,
                "column": "Provincia"
              }
            ]
          }
        ]
      },
      {
        "name": "dim Atributos_Costes",
        "columns": [
          {
            "name": "Id_Costes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Costes",
            "isAvailableInMdx": false
          },
          {
            "name": "Clase de factura",
            "dataType": "string",
            "sourceColumn": "Clase de factura",
            "isAvailableInMdx": false
          },
          {
            "name": "Motivo de pedido (motivo de la operación)",
            "dataType": "string",
            "sourceColumn": "Motivo de pedido (motivo de la operación)",
            "isAvailableInMdx": false
          },
          {
            "name": "Clase de operación",
            "dataType": "string",
            "sourceColumn": "Clase de operación",
            "isAvailableInMdx": false
          },
          {
            "name": "División",
            "dataType": "string",
            "sourceColumn": "División",
            "isAvailableInMdx": false
          },
          {
            "name": "Sociedad CO",
            "dataType": "string",
            "sourceColumn": "Sociedad CO",
            "isAvailableInMdx": false
          },
          {
            "name": "Version Plan",
            "dataType": "string",
            "sourceColumn": "Version Plan",
            "isAvailableInMdx": false
          },
          {
            "name": "Indicador plan/real",
            "dataType": "string",
            "sourceColumn": "Indicador plan/real",
            "isAvailableInMdx": false
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Atributos_Costes = Source{[Schema=\"dim\",Item=\"Atributos_Costes\"]}[Data]",
                "in",
                "    dim_Atributos_Costes"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Material",
        "columns": [
          {
            "name": "Id_Material",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Material"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_MATERIAL",
            "dataType": "string",
            "sourceColumn": "BK_MATERIAL"
          },
          {
            "name": "BK_TipoMaterial",
            "dataType": "string",
            "sourceColumn": "BK_TipoMaterial"
          },
          {
            "name": "BK_Ramo",
            "dataType": "string",
            "sourceColumn": "BK_Ramo"
          },
          {
            "name": "BK_GrupoArticulos",
            "dataType": "string",
            "sourceColumn": "BK_GrupoArticulos"
          },
          {
            "name": "Nombre Material",
            "dataType": "string",
            "sourceColumn": "Nombre Material"
          },
          {
            "name": "UM Material",
            "dataType": "string",
            "sourceColumn": "UM Material"
          },
          {
            "name": "Grupo Articulos",
            "dataType": "string",
            "sourceColumn": "Grupo Articulos"
          },
          {
            "name": "Nombre Grupo",
            "dataType": "string",
            "sourceColumn": "Nombre Grupo"
          },
          {
            "name": "Jerarquía",
            "dataType": "string",
            "sourceColumn": "Jerarquía"
          },
          {
            "name": "Calidad",
            "dataType": "string",
            "sourceColumn": "Calidad"
          },
          {
            "name": "Digital",
            "dataType": "string",
            "sourceColumn": "Digital"
          },
          {
            "name": "AltaCalidad",
            "dataType": "string",
            "sourceColumn": "AltaCalidad"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Material = Source{[Schema=\"dim\",Item=\"Material\"]}[Data]",
                "in",
                "    dim_Material"
              ]
            }
          }
        ]
      },
      {
        "name": "Fecha",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Id_Fecha",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Id_Fecha]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Año",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Año]",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mes",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Mes]",
            "sortByColumn": "MesNro"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MesNro",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "sourceColumn": "[MesNro]",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TrimNro",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "sourceColumn": "[TrimNro]",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trimestre",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Trimestre]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Semestre",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Semestre]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortMonthYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortMonthYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "M-Y",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[M-Y]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortTrimYear",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortTrimYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "T-Y",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[T-Y]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fecha",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fecha]",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mes 2",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Mes 2]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                " ",
                "VAR Calendario = FILTER(CALENDAR(",
                "    DATE( 2018, 1, 1),",
                "    DATE( 2021, 12, 31)),DAY([Date]) = 1)",
                "    ",
                "  ",
                " Return  SELECTCOLUMNS(",
                "    Calendario,",
                "    \"Fecha\",[DATE],",
                "    \"Id_Fecha\",  YEAR( [Date] ) * 1000 + MONTH( [Date] ),",
                "    \"Año\", YEAR( [Date] ),",
                "    \"Mes\", UPPER( FORMAT( [Date], \"MMMM\" ) ),",
                "    \"MesNro\", INT( FORMAT( [Date], \"M\" ) ),",
                "    \"TrimNro\", ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"Trimestre\", \"T\" & ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"Semestre\", \"S\" & ROUNDUP( MONTH( [Date] ) / 6, 0),",
                "    \"SortMonthYear\", YEAR( [Date] ) * 100 + MONTH( [Date] ),",
                "    \"M-Y\" , UPPER( FORMAT( [Date], \"MMM\" ) ) & \"-\" & RIGHT(YEAR( [Date] ),2),",
                "    \"SortTrimYear\", YEAR( [Date] ) * 100 + ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"T-Y\" , \"T\" & ROUNDUP( MONTH( [Date] ) / 3, 0 ) & \"-\" & RIGHT(YEAR( [Date] ),2),",
                "     \"Mes 2\", UPPER( FORMAT( [Date], \"MMMM\" ) )",
                "    )",
                "    "
              ]
            }
          }
        ]
      },
      {
        "name": "dim Centro",
        "columns": [
          {
            "name": "Id_Centro",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Centro"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_SPRAS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_SPRAS"
          },
          {
            "name": "BK_PAIS",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PAIS"
          },
          {
            "name": "BK_CENTRO",
            "dataType": "string",
            "sourceColumn": "BK_CENTRO"
          },
          {
            "name": "BK_CLIENTE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_CLIENTE"
          },
          {
            "name": "BK_PROVEEDOR",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_PROVEEDOR"
          },
          {
            "name": "Nombre Centro",
            "dataType": "string",
            "sourceColumn": "Nombre Centro"
          },
          {
            "name": "Nombre Centro 2",
            "dataType": "string",
            "sourceColumn": "Nombre Centro 2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Centro = Source{[Schema=\"dim\",Item=\"Centro\"]}[Data]",
                "in",
                "    dim_Centro"
              ]
            }
          }
        ]
      },
      {
        "name": "fact Costes_Plan",
        "columns": [
          {
            "name": "CLV_Mandante",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Mandante",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Tipo de moneda para una sociedad PA",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Tipo de moneda para una sociedad PA",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Clase de operación",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Clase de operación",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Versión plan (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Versión plan (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Período/Año",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Período/Año",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Número para objetos PA (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Número para objetos PA (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Historial de modificación para objetos PA (CO-PA)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Historial de modificación para objetos PA (CO-PA)",
            "isAvailableInMdx": false
          },
          {
            "name": "CLV_Nº de documento del cálculo de resultados de prtd.individual",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLV_Nº de documento del cálculo de resultados de prtd.individual",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste Producto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste Producto",
            "isAvailableInMdx": false
          },
          {
            "name": "Volumen de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Volumen de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Ingresos",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ingresos",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Ctd. imputación",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Ctd. imputación",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Precio Input",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Precio Input",
            "isAvailableInMdx": false
          },
          {
            "name": "Desviac.Estructura",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desviac.Estructura",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Ctd. a emplear",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Ctd. a emplear",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Restante input",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Restante input",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.precio imputac.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.precio imputac.",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Costes Fijos",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Costes Fijos",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappels",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappels",
            "isAvailableInMdx": false
          },
          {
            "name": "Descuentos ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Descuentos ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Descuento por pronto pago",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Descuento por pronto pago",
            "isAvailableInMdx": false
          },
          {
            "name": "Diferencia de precio",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Diferencia de precio",
            "isAvailableInMdx": false
          },
          {
            "name": "Comisión de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Comisión de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Precio estándar",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Precio estándar",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos generales de ventas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos generales de ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos generales de gestión",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos generales de gestión",
            "isAvailableInMdx": false
          },
          {
            "name": "Desviacion Restante",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desviacion Restante",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv.Rechazo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv.Rechazo",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra de troqueles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra de troqueles",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra de cliches",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra de cliches",
            "isAvailableInMdx": false
          },
          {
            "name": "Materias primas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Materias primas",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappels Compras",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappels Compras",
            "isAvailableInMdx": false
          },
          {
            "name": "Desv. Precio Mixto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Desv. Precio Mixto",
            "isAvailableInMdx": false
          },
          {
            "name": "Estr. Administración",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estr. Administración",
            "isAvailableInMdx": false
          },
          {
            "name": "Logística Cargas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Logística Cargas",
            "isAvailableInMdx": false
          },
          {
            "name": "Crédito y Caución",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Crédito y Caución",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste vtas cogen.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste vtas cogen.",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Cogeneración",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Cogeneración",
            "isAvailableInMdx": false
          },
          {
            "name": "Estructura Comercial",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estructura Comercial",
            "isAvailableInMdx": false
          },
          {
            "name": "Chep Palet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Chep Palet",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Extraord.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Extraord.",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Financieros",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Financieros",
            "isAvailableInMdx": false
          },
          {
            "name": "Estructura General",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Estructura General",
            "isAvailableInMdx": false
          },
          {
            "name": "Impuesto s/bº",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Impuesto s/bº",
            "isAvailableInMdx": false
          },
          {
            "name": "Ing. Extraordinarios",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ing. Extraordinarios",
            "isAvailableInMdx": false
          },
          {
            "name": "Ingresos Financieros",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ingresos Financieros",
            "isAvailableInMdx": false
          },
          {
            "name": "Coste de Montaje",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Coste de Montaje",
            "isAvailableInMdx": false
          },
          {
            "name": "Canon Plaform",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Canon Plaform",
            "isAvailableInMdx": false
          },
          {
            "name": "Transporte Externo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Transporte Externo",
            "isAvailableInMdx": false
          },
          {
            "name": "Transporte Interno",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Transporte Interno",
            "isAvailableInMdx": false
          },
          {
            "name": "Cantidad en M2",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Cantidad en M2",
            "isAvailableInMdx": false
          },
          {
            "name": "Rappel en Pedido",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rappel en Pedido",
            "isAvailableInMdx": false
          },
          {
            "name": "Compra Utiles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Compra Utiles",
            "isAvailableInMdx": false
          },
          {
            "name": "Mapfre",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Mapfre",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos Montadora",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos Montadora",
            "isAvailableInMdx": false
          },
          {
            "name": "Gastos recorte",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gastos recorte",
            "isAvailableInMdx": false
          },
          {
            "name": "Dtos PP Compras",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Dtos PP Compras",
            "isAvailableInMdx": false
          },
          {
            "name": "Merma real",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Merma real",
            "isAvailableInMdx": false
          },
          {
            "name": "Merma teórica",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Merma teórica",
            "isAvailableInMdx": false
          },
          {
            "name": "C.Transp.Teórico",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "C.Transp.Teórico",
            "isAvailableInMdx": false
          },
          {
            "name": "Rec.Multsdad",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rec.Multsdad",
            "isAvailableInMdx": false
          },
          {
            "name": "Ineficiencias PP 1",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ineficiencias PP 1",
            "isAvailableInMdx": false
          },
          {
            "name": "Gast.dir.Cogenerac.",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Gast.dir.Cogenerac.",
            "isAvailableInMdx": false
          },
          {
            "name": "Margen Rentabilidad",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Margen Rentabilidad",
            "isAvailableInMdx": false
          },
          {
            "name": "Montaje",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Montaje",
            "isAvailableInMdx": false
          },
          {
            "name": "Papeles",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Papeles",
            "isAvailableInMdx": false
          },
          {
            "name": "Pdtos Ondulados",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Pdtos Ondulados",
            "isAvailableInMdx": false
          },
          {
            "name": "Tintas",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Tintas",
            "isAvailableInMdx": false
          },
          {
            "name": "Palets",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Palets",
            "isAvailableInMdx": false
          },
          {
            "name": "Aprov. Varios",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Aprov. Varios",
            "isAvailableInMdx": false
          },
          {
            "name": "Actividad Externa",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Actividad Externa",
            "isAvailableInMdx": false
          },
          {
            "name": "Costes Estructura",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Costes Estructura",
            "isAvailableInMdx": false
          },
          {
            "name": "MOD",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MOD",
            "isAvailableInMdx": false
          },
          {
            "name": "Horas Máquina",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Horas Máquina",
            "isAvailableInMdx": false
          },
          {
            "name": "Reserva 2",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Reserva 2",
            "isAvailableInMdx": false
          },
          {
            "name": "Reserva 3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Reserva 3",
            "isAvailableInMdx": false
          },
          {
            "name": "Peso bruto",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Peso bruto",
            "isAvailableInMdx": false
          },
          {
            "name": "Condición Zuni",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Condición Zuni",
            "isAvailableInMdx": false
          },
          {
            "name": "Recargo Lidl",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Recargo Lidl",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Organizacion_Ventas",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Organizacion_Ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Clientes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Clientes",
            "isAvailableInMdx": false
          },
          {
            "name": "Id Zona_Ventas",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id Zona_Ventas",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Costes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Costes",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Material",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Material",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Centro",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Centro",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Sociedad",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Sociedad",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Sectores",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Sectores",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Fecha",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Id_Fecha",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Divisiones",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Divisiones",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Ramo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Ramo",
            "formatString": "#,##0",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Coste_Plan",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Coste_Plan",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Atributos_Materiales_PROVISIONAL",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Atributos_Materiales_PROVISIONAL",
            "isAvailableInMdx": false
          },
          {
            "name": "Id_Atributos_Ramo_PROVISIONAL",
            "dataType": "int64",
            "sourceColumn": "Id_Atributos_Ramo_PROVISIONAL"
          },
          {
            "name": "Id_Personal 1",
            "dataType": "int64",
            "sourceColumn": "Id_Personal 1"
          },
          {
            "name": "Id_Personal 2",
            "dataType": "int64",
            "sourceColumn": "Id_Personal 2"
          },
          {
            "name": "Id_Proveedor 1",
            "dataType": "int64",
            "sourceColumn": "Id_Proveedor 1"
          },
          {
            "name": "Id_Proveedor 2",
            "dataType": "int64",
            "sourceColumn": "Id_Proveedor 2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    fact_Costes_Plan = Source{[Schema=\"fact\",Item=\"Costes_Plan\"]}[Data]",
                "in",
                "    fact_Costes_Plan"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Cantidad M2 (Plan)",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Cantidad en M2] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "€ Ingresos Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ C.Transp.Teórico Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[C.Transp.Teórico] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Rec. Multsdad Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Rec.Multsdad] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"V\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Abono Mala Calidad Plan",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Motivo de pedido (motivo de la operación)] = \"Z01\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Ingresos Totales Plan",
            "expression": "( [€ Ingresos Plan] + [€ C.Transp.Teórico Plan] + [€ Rec. Multsdad Plan] ) - [€ Abono Mala Calidad Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Abono Roto montad. Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Clase de factura] >= \"ZG21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZG24\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Descuentos Ventas Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Descuentos ventas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"B\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Dtos Rotos Montadora Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Merma real] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Rappels Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Rappels] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Venta Neta Plan",
            "expression": "( ( [Ingresos Totales Plan] - [€ Descuentos Ventas Plan] ) + [€ Rappels Plan] + [€ Abono Roto montad. Plan] + [€ Abono Mala Calidad Plan] ) - [€ Dtos Rotos Montadora Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste Producto Plan",
            "expression": [
              "",
              "",
              "/* El Pr  Estandar en el Plan no tiene valor. Se calcula con el Coste Procuto y Precio Estandar del REAL */",
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Coste Producto] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"IV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IVS1\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZV01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZS1V\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZS4V\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0000999999\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"0\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Precio Estandar Plan",
            "expression": [
              "",
              "",
              "/* El Pr  Estandar en el Plan no tiene valor. Se calcula con el Coste Procuto y Precio Estandar del REAL */",
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Precio estándar] ),",
              "    'dim Atributos_Costes'[Clase de factura] >= \"AA\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"FZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"IG01\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"IVS4\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"LG\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"SV04\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZF21\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZF23\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"H00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"KZZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"M00\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZFZ\"",
              "        || 'dim Atributos_Costes'[Clase de factura] >= \"ZH0\"",
              "        && 'dim Atributos_Costes'[Clase de factura] <= \"ZZZ\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"C\",",
              "    'dim Clientes'[BK_CLIENTE] >= \"0000000001 \"",
              "        && 'dim Clientes'[BK_CLIENTE] <= \"0000999999\",",
              "    'dim Material'[BK_GrupoArticulos] >= \"AALMI\"",
              "        && 'dim Material'[BK_GrupoArticulos] <= \"EFLEJE\"",
              "        || 'dim Material'[BK_GrupoArticulos] >= \"EVARI\"",
              "        && 'dim Material'[BK_GrupoArticulos] <= \"ZVARIOS\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Pr. Estándar Plan",
            "expression": "( ( [€ Coste Producto] + [€ Precio Estandar] ) / [Total Cantidad M2 (Real)] ) * [Total Cantidad M2 (Plan)]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "SIN DEFINIR--> Desv. PP Plan",
            "description": "ZCTARPLAN _ Cta de Rdos/Plan",
            "expression": [
              "0",
              "/* NO existe la columna Desv. PP que es la que define la medida:  CALCULATE( SUM('fact Costes_Plan'[Ingresos]) , 'dim Atributos_Costes'[Indicador plan/real] =\"1\",'dim Atributos_Costes'[Clase de operación] = \"C\") */"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Industrial Plan",
            "expression": "( [Venta Neta Plan] - [Pr. Estándar Plan] ) - [SIN DEFINIR--> Desv. PP Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Comision de Ventas Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Comisión de ventas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Transporte Interno Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Transporte Interno] ),",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Transporte Externo Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Transporte Externo] ),",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Transp. Total Plan",
            "expression": "[€ Transporte Interno Plan] + [€ Transporte Externo Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Canon Plaform Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Canon Plaform] ),",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Chep Palet Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Chep Palet] ),",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Coste de Montaje Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Coste de Montaje] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Seguro Caucion Plan",
            "expression": "[€ Credito y Caucion Plan] + [€ Mapfre Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Credito y Caucion Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Crédito y Caución] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Mapfre Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Mapfre] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Compra Troqueles Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Compra de troqueles] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Compra de Cliches Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Compra de cliches] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gast. dir. Cogenerac. Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Gast.dir.Cogenerac.] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Recorte  Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Gastos recorte] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"B\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Contribucion Plan",
            "expression": " [Margen Industrial Plan] -( [€ Comision de Ventas Plan] + [€ Transporte Interno Plan] + [€ Transporte Externo Plan] + [€ Canon Plaform Plan] + [€ Chep Palet Plan] + [€ Coste de Montaje Plan] + [€ Credito y Caucion Plan] + [€ Compra Troqueles Plan] + [€ Compra de Cliches Plan] + [€ Gastos Recorte  Plan] + [€ Mapfre Plan] + [€ Gast. dir. Cogenerac. Plan] )",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura Comercial Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Estructura Comercial] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Atributos_Costes'[Sociedad CO] =\"1000\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Logistica Carga/Mtto Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Logística Cargas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Montadora Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Gastos Montadora] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura Oficinas Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Estr. Administración] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Estructura General Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Estructura General] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Cogeneracion Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Gastos Cogeneración] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Operativo Plan",
            "expression": " [Margen Contribucion Plan] - ( [€ Logistica Carga/Mtto Plan] + [€ Gastos Montadora Plan] + [€ Estructura Oficinas Plan] + [€ Estructura General Plan] + [€ Gastos Cogeneracion Plan] + [€ Estructura Comercial Plan])",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ingresos Fi/SD Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    --'Materiales'[BK_MATERIAL] = \"000000000000140046\"",
              "    'dim Material'[BK_MATERIAL] = \"000000000000140046\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ing. Financ. Total  Plan",
            "expression": " [€ Ingresos Fi/SD Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Gastos Financieros Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Gastos Financieros] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Descuento por Pronto Pago Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Descuento por pronto pago] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"D\"",
              "        || 'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Neto Plan",
            "expression": " ( ( [Margen Operativo Plan] - [€ Gastos Financieros Plan] ) - [€ Descuento por Pronto Pago Plan] ) + [€ Ingresos Fi/SD Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Ing. Extraordin. Total",
            "expression": " [€ Ingresos Ext/sd Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "€ Ingresos Ext/sd Plan",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Ingresos] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\",",
              "    'dim Material'[BK_MATERIAL] = \"000000000000140140\"",
              "    --'Materiales'[BK_MATERIAL] = \"000000000000140140\"",
              ")",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Margen Final Plan",
            "expression": " [Margen Neto Plan] + [€ Ingresos Ext/sd Plan]",
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Cantidad UD (Plan)",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'fact Costes_Plan'[Volumen de ventas] ),",
              "    'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "    'dim Atributos_Costes'[Version Plan] = \"000\",",
              "    'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Venta Neta Plan (No Hierar)",
            "expression": [
              "VAR _Ventas =",
              "    ( ( [Ingresos Totales Plan] - [€ Descuentos Ventas Plan] ) + [€ Rappels Plan] + [€ Abono Roto montad. Plan]",
              "        + [€ Abono Mala Calidad Plan] )",
              "        - [€ Dtos Rotos Montadora Plan]",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Ventas",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Cantidad M2 (Plan) (No Hierar)",
            "expression": [
              "VAR _Nivel2= IF( SELECTEDVALUE( Ramo_Industrial[DescripcionNivel2] ) = \"\", 1, 0 ) ",
              "",
              "VAR _Nivel3= IF( SELECTEDVALUE( Ramo_Industrial[DescripcionNivel3] ) = \"\", 1, 0 ) ",
              "",
              "VAR _Cantidad =",
              "    CALCULATE(",
              "        SUM( 'fact Costes_Plan'[Cantidad en M2] ),",
              "        'dim Atributos_Costes'[Clase de operación] = \"F\",",
              "        'dim Atributos_Costes'[Version Plan] = \"000\",",
              "        'dim Atributos_Costes'[Indicador plan/real] = \"1\"",
              "    )",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE(),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "        _Nivel3 = 1 ),",
              "    ",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "         _Nivel2 = 1 ),",
              "            BLANK( ),",
              "        _Cantidad",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "dim Sociedades",
        "columns": [
          {
            "name": "Id_Sociedad",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Sociedad"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_SOCIEDAD",
            "dataType": "string",
            "sourceColumn": "BK_SOCIEDAD"
          },
          {
            "name": "Sociedad",
            "dataType": "string",
            "sourceColumn": "Sociedad"
          },
          {
            "name": "Poblacion",
            "dataType": "string",
            "sourceColumn": "Poblacion"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Sociedades = Source{[Schema=\"dim\",Item=\"Sociedades\"]}[Data]",
                "in",
                "    dim_Sociedades"
              ]
            }
          }
        ]
      },
      {
        "name": "Metricas visuales",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Id",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": false,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Metricas",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH('Metricas visuales'[Id],",
              "1,\"Venta Neta\",",
              "2,\"M2\",",
              "3,\"UD\",",
              "4,\"Venta neta \",",
              "5,\"% Margen Final\",",
              "6,\"% Margen Final \"",
              ")",
              "/*",
              "    IF (",
              "        'Metricas visuales'[Id] = 2,",
              "        \"M2\",",
              "           IF (",
              "       \t 'Metricas visuales'[Id] = 3,",
              "       \t \"UD\",",
              "       \t IF (",
              "          \t  'Metricas visuales'[Id] = 4,",
              "            \t\"Venta Neta \", \"\" )",
              "            )",
              "        )",
              "    )",
              " ",
              "    */    ",
              "      "
            ],
            "sortByColumn": "Id"
          },
          {
            "type": "calculated",
            "name": "Seleccion Sociedad",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " 0"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " /* {1,2,3,4,5,6}*/ {1,2,3,4,5,6}"
            }
          }
        ],
        "measures": [
          {
            "name": "Resultado Real",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales'[Id] ),",
              "    1, [Venta Neta],",
              "    2, [Total Cantidad M2 (Real)],",
              "    3, [Total Cantidad UD (Real)],",
              "    4, [Venta Neta BO],",
              "    5, [% Margen Final BO] * 100,",
              "    6, [% Margen Final BO UNI] * 100",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Resultado Plan",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales'[Id] ),",
              "    1, [Venta Neta Plan],",
              "    2, [Total Cantidad M2 (Plan)],",
              "    3, [Total Cantidad UD (Plan)],",
              "    4, [Venta Neta Plan]",
              "/*,",
              "    3, [Margen Contribucion Plan] ,",
              "    4, [Margen Final Plan],",
              "    5, [% Margen Final]",
              "    */",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Real YTD",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales'[Id] ),",
              "    1, CALCULATE( [Venta Neta], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    2, CALCULATE( [Total Cantidad M2 (Real)], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    3, CALCULATE( [Total Cantidad UD (Real)], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    4, CALCULATE( [Venta Neta BO], DATESYTD( 'dim Fechas'[Fecha] ) )",
              "/* ,",
              "    5, CALCULATE( [% Margen Final],DATESYTD(Fechas[Fecha]))",
              "    */",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Plan YTD",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales'[Id] ),",
              "    1, CALCULATE( [Venta Neta Plan], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    2, CALCULATE( [Total Cantidad M2 (Plan)], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    3, CALCULATE( [Total Cantidad UD (Plan)], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    4, CALCULATE( [Venta Neta Plan], DATESYTD( 'dim Fechas'[Fecha] ) )",
              "/*,",
              "    3, CALCULATE([Margen Contribucion Plan],DATESYTD(Fechas[Fecha])),",
              "    4, CALCULATE([Margen Final Plan],DATESYTD(Fechas[Fecha])) ,",
              "    5, CALCULATE( [% Margen Final],DATESYTD(Fechas[Fecha]))",
              "    */",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Real YTD / Dia",
            "expression": " DIVIDE([Real YTD],[Dias])",
            "formatString": "#,0"
          },
          {
            "name": "Ingresos Totales Plan YTD",
            "expression": [
              "VAR _DIAS = CALCULATE( DISTINCTCOUNT( 'dim Fechas'[Fecha] ), 'dim Fechas'[DiaSemana] < 6 )",
              "VAR _Promedio = DIVIDE( [Ingresos Totales Plan], _DIAS )",
              "VAR _YTD = CALCULATE( [Ingresos Totales], DATESYTD( 'dim Fechas'[Fecha] ) )",
              "RETURN",
              "    _Promedio"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Dias",
            "expression": "CALCULATE( DISTINCTCOUNT( 'dim Fechas'[Fecha] ), 'dim Fechas'[DiaSemana] < 6 )"
          },
          {
            "name": "Plan YTD / Dia",
            "expression": " DIVIDE([Plan YTD],[Dias])",
            "formatString": "#,0"
          },
          {
            "name": "Real  SPLY",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales'[Id] ),",
              "    1, CALCULATE( [Venta Neta], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ) ),",
              "    2, CALCULATE( [Total Cantidad M2 (Real)], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ) ),",
              "    3, CALCULATE( [Total Cantidad UD (Real)], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ) )",
              "/*,",
              "    4, CALCULATE([Margen Final],SAMEPERIODLASTYEAR(Fechas[Fecha])) ,",
              "    5, CALCULATE( [% Margen Final],SAMEPERIODLASTYEAR(Fechas[Fecha]))",
              "    */",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Dif SPLY",
            "expression": " [Resultado Real]-[Real  SPLY]",
            "formatString": "#,0"
          },
          {
            "name": "RNK Top 5",
            "expression": [
              " RANKX(ALL('dim Clientes'),[Dif SPLY],,DESC,Dense)",
              " "
            ]
          },
          {
            "name": "RNK Down 5",
            "expression": [
              " RANKX(ALL('dim Clientes'),[Dif SPLY],,ASC,Dense)",
              " "
            ]
          },
          {
            "name": "RANK Agrupado",
            "expression": [
              "VAR _Top5 = RANKX( ALL( 'dim Clientes' ), [Dif SPLY], , DESC, DENSE )",
              "VAR _Down5 = RANKX( ALL( 'dim Clientes' ), [Dif SPLY], , ASC, DENSE )",
              "RETURN",
              "    IF( _Top5 <= 10, \"TOP5\", IF( _Down5 <= 10, \"DOWN5\", \"RESTO\" ) )"
            ]
          },
          {
            "name": "% Real s / SPLY",
            "expression": "DIVIDE( [Resultado Real], [Real  SPLY] ) - 1",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Dif Plan vs Real",
            "expression": "[Resultado Real] - [Resultado Plan]",
            "formatString": "#,0"
          },
          {
            "name": "Visualizacion 1",
            "expression": [
              "SWITCH(",
              "    TRUE( ),",
              "    MAX( 'Metricas visuales'[Id] ) = 1 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 1 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 2 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 2 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 3 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 3 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 4 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 4 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 0,",
              "    BLANK( )",
              ")"
            ]
          },
          {
            "name": "Visual % Margen",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "\t SELECTEDVALUE('dim Sociedades'[BK_SOCIEDAD])=\"15\",[% Margen Final BO UNI],",
              "\tSELECTEDVALUE('dim Sociedades'[BK_SOCIEDAD])<>\"15\",[% Margen Final BO]",
              "\t)",
              "",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Visual Margen",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "\t SELECTEDVALUE('dim Sociedades'[BK_SOCIEDAD])=\"15\",[Margen Final BO UNI],",
              "\tSELECTEDVALUE('dim Sociedades'[BK_SOCIEDAD])<>\"15\",[Margen Final BO]",
              "\t)"
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Titulo VAR1",
            "expression": [
              "",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sociedad = SELECTEDVALUE ( 'dim Sociedades'[Poblacion] )",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth=_LastMonth,  \"Análisis Rentabilidad de Venta en \" & _Month & \" de \" & _Year & \"  en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth<>_LastMonth,  \"Análisis Rentabilidad de Venta en \" & \"[ Varios Meses ]\" & \" de \" & _Year & \" en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Month ) ), \"Análisis Rentabilidad de Venta en \" & _Month & \" de \" & _Year,",
              "        NOT ( ISBLANK ( _Year ) ), \"Análisis Rentabilidad de Venta en \" & _Year,",
              "        \"Análisis Rentabilidad de Venta\"",
              "    )",
              "RETURN",
              "    _Result"
            ]
          },
          {
            "name": "Titulo VAR Detalle",
            "expression": " \"Detalle Coste - \" & [Titulo VAR1]"
          },
          {
            "name": "Titulo Tarjeta Metricas 1",
            "expression": [
              " ",
              "VAR _Metricas = SELECTEDVALUE('Metricas visuales Costes'[Metricas Costes])",
              "",
              "RETURN ",
              "",
              "_Metricas & \" vs PLAN\"",
              ""
            ]
          },
          {
            "name": "Titulo Tarjeta Metricas 2",
            "expression": [
              " ",
              "VAR _Metricas = SELECTEDVALUE('Metricas visuales Costes'[Metricas Costes])",
              "VAR _SelectedYear = SELECTEDVALUE('dim Fechas'[Año])",
              "VAR _PreviousYear = SELECTEDVALUE('dim Fechas'[Año])-1",
              "",
              "RETURN ",
              "",
              "_Metricas & \" \" & _SelectedYear & \" vs \" & _PreviousYear"
            ]
          },
          {
            "name": "Titulo VAR Clientes",
            "expression": [
              "",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sociedad = SELECTEDVALUE ( 'dim Sociedades'[Poblacion] )",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth=_LastMonth,  \"Análisis Rentabilidad Clientes en \" & _Month & \" de \" & _Year & \"  en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth<>_LastMonth,  \"Análisis Rentabilidad Clientes en \" & \"[ Varios Meses ]\" & \" de \" & _Year & \" en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Month ) ), \"Análisis Rentabilidad Clientes en \" & _Month & \" de \" & _Year,",
              "        NOT ( ISBLANK ( _Year ) ), \"Análisis Rentabilidad Clientes en \" & _Year,",
              "        \"Análisis Rentabilidad Clientes\"",
              "    )",
              "RETURN",
              "    _Result"
            ]
          },
          {
            "name": "Titulo VAR Geografia",
            "expression": [
              "",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sociedad = SELECTEDVALUE ( 'dim Sociedades'[Poblacion] )",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth=_LastMonth,  \"Análisis Rentabilidad por Zona Geográfica en \" & _Month & \" de \" & _Year & \"  en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Sociedad ) )&& _FirstMonth<>_LastMonth,  \"Análisis Rentabilidad por Zona Geográfica en \" & \"[ Varios Meses ]\" & \" de \" & _Year & \" en \" & _Sociedad,",
              "        NOT ( ISBLANK ( _Month ) ), \"Análisis Rentabilidad por Zona Geográfica en \" & _Month & \" de \" & _Year,",
              "        NOT ( ISBLANK ( _Year ) ), \"Análisis Rentabilidad por Zona Geográfica en \" & _Year,",
              "        \"Análisis Rentabilidad por Zona Geográfica\"",
              "    )",
              "RETURN",
              "    _Result"
            ]
          },
          {
            "name": "Titulo Ventas Mensuales",
            "expression": [
              " ",
              "VAR _Metricas = SWITCH(SELECTEDVALUE('Metricas visuales'[Id]),1,\"Euros\",2,\"M2\",\"Otros\")",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sector = SELECTEDVALUE('dim Sectores'[Descripcion Sector])",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT (ISBLANK(_FirstMonth=_LastMonth)),  \"Informe Resultado en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &  _Month & \" de \" & _Year,",
              "        NOT (ISBLANK( _FirstMonth<>_LastMonth)),   \"Informe Resultado en \" & _Metricas & \" del Sector \"  & _Sector & \" en\" & \"[ Varios Meses ]\" & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Month ) ),  \"Informe Resultado en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &_Month & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Year ) ),  \"Informe Resultado en \" & _Metricas & \" del Sector \"  & _Sector & \" en \" & _Year,",
              "        \"Informe Resultado en \" & _Metricas & \" del Sector \" & _Sector ",
              "    )",
              "    ",
              "RETURN",
              "",
              "_Result",
              ""
            ]
          },
          {
            "name": "Visualizacion 2",
            "expression": [
              "SWITCH(",
              "    TRUE( ),",
              "    MAX( 'Metricas visuales'[Id] ) = 1 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 1 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 2 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 2 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 3 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 3 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 4 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 4 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 5 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 0,",
              "    MAX( 'Metricas visuales'[Id] ) = 5 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 6 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) = \"15\", 1,",
              "    MAX( 'Metricas visuales'[Id] ) = 6 && SELECTEDVALUE( 'dim Sociedades'[BK_SOCIEDAD] ) <> \"15\", 2,",
              "    BLANK( )",
              ")"
            ]
          },
          {
            "name": "Titulo Grafico Historico Ventas",
            "expression": [
              "VAR _Metricas = SELECTEDVALUE( 'Metricas visuales'[Metricas] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Real vs Plan de \" & _Metricas & \" en \" & _Year"
            ]
          },
          {
            "name": "Real vs Real SPLY (m2)",
            "expression": [
              "VAR _SPLY =",
              "    CALCULATE(",
              "        [Total Cantidad M2 (Real)],",
              "        SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] )",
              "    )",
              "RETURN",
              "    [Total Cantidad M2 (Real)] - _SPLY"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "Real vs Real SPLY (€)",
            "expression": [
              "VAR _SPLY =",
              "    CALCULATE(",
              "        [Venta Neta],",
              "        SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] )",
              "    )",
              "RETURN",
              "    [Venta Neta] - _SPLY"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "Titulo Desglose Zona Geografica",
            "expression": [
              "VAR _Metricas = SELECTEDVALUE( 'Metricas visuales'[Metricas] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Análisis de \" & _Metricas & \" por Zona Geográfica en \" & _Year"
            ]
          },
          {
            "name": "Titulo Desglose Ramo Industrial",
            "expression": [
              "VAR _Metricas = SELECTEDVALUE( 'Metricas visuales'[Metricas] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Análisis de \" & _Metricas & \" por Ramo Industrial en \" & _Year"
            ]
          },
          {
            "name": "Titulo Desglose Familia",
            "expression": [
              "VAR _Metricas = SELECTEDVALUE( 'Metricas visuales'[Metricas] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Análisis de \" & _Metricas",
              "        & \" por Familia de Materiales en \"",
              "        & _Year                       "
            ]
          },
          {
            "name": "Titulo Desglose Sector",
            "expression": [
              "VAR _Metricas = SELECTEDVALUE( 'Metricas visuales'[Metricas] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Análisis de \" & _Metricas",
              "        & \" por Sectores en \"",
              "        & _Year                       "
            ]
          },
          {
            "name": "Real vs Real SPLY (€) (No Hierar)",
            "expression": [
              "VAR _SPLY = CALCULATE( [Venta Neta], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ) )",
              "",
              "VAR _Result1 = [Venta Neta] - _SPLY",
              "",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Result1",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "Real vs Real SPLY (m2) (No Hierar)",
            "expression": [
              "VAR _SPLY = CALCULATE( [Total Cantidad M2 (Real)], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ) )",
              "",
              "VAR _Result1 = [Total Cantidad M2 (Real)] - _SPLY",
              "",
              "VAR _Result =",
              "    SWITCH(",
              "        TRUE( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel3] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel3] ) )",
              "        ),",
              "            BLANK( ),",
              "        AND(",
              "            ISINSCOPE( Ramo_Industrial[DescripcionNivel2] ),",
              "            ISBLANK( VALUES( Ramo_Industrial[DescripcionNivel2] ) )",
              "        ),",
              "            BLANK( ),",
              "        _Result1",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0"
          }
        ]
      },
      {
        "name": "dim Sectores",
        "columns": [
          {
            "name": "Id_Sectores",
            "dataType": "int64",
            "description": "Columna duplicada para diferenciar paginas detalle de los informes de ventas",
            "isHidden": true,
            "sourceColumn": "Id_Sectores"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_CODRAMO",
            "dataType": "string",
            "sourceColumn": "BK_CODRAMO"
          },
          {
            "name": "Descripcion Sector",
            "dataType": "string",
            "sourceColumn": "Descripcion Sector"
          },
          {
            "name": "Sectores Agrupados",
            "dataType": "string",
            "sourceColumn": "Sectores Agrupados"
          },
          {
            "name": "Descripcion Sector1",
            "dataType": "string",
            "sourceColumn": "Descripcion Sector"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Sectores = Source{[Schema=\"dim\",Item=\"Sectores\"]}[Data]",
                "in",
                "    dim_Sectores"
              ]
            }
          }
        ]
      },
      {
        "name": "Fechas",
        "isHidden": true,
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Fecha",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Fecha]",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Año",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Año]",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mes",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Mes]",
            "sortByColumn": "MesNro"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MesNro",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MesNro]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "NroDia",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[NroDia]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DiaSemana",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[DiaSemana]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "NroSemana",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[NroSemana]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Semana",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Semana]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fin de Semana",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fin de Semana]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "Nombre Dia",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Nombre Dia]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TrimNro",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[TrimNro]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Trimestre",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Trimestre]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SemNro",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SemNro]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Semestre",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Semestre]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Desvio Dia",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Desvio Dia]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortMonthYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortMonthYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "M-Y",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[M-Y]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortTrimYear",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortTrimYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "T-Y",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[T-Y]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortSemYear",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[SortSemYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "S-Y",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[S-Y]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Mes2",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Mes2]",
            "sortByColumn": "MesNro"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                " ",
                "VAR Calendario = CALENDAR(",
                "    DATE( 2018, 1, 1),",
                "    DATE( 2023, 12, 31)",
                ") return SELECTCOLUMNS(",
                "   Calendario,",
                "    \"Fecha\", [Date],",
                "    \"Año\", YEAR( [Date] ),",
                "    \"Mes\", UPPER( FORMAT( [Date], \"MMMM\" ) ),",
                "    \"MesNro\", INT( FORMAT( [Date], \"M\" ) ),",
                "    \"NroDia\", INT( FORMAT( [Date], \"d\" ) ),",
                "    \"DiaSemana\", WEEKDAY( [Date], 2 ),",
                "    \"NroSemana\", WEEKNUM( [Date], 21 ),",
                "    \"Semana\", \"Semana \" & WEEKNUM( [Date],21),",
                "    \"Fin de Semana\", WEEKDAY( [Date], 2 ) IN {6,7},",
                "    \"Nombre Dia\", UPPER( FORMAT( [Date], \"DDDD\" ) ),",
                "    \"TrimNro\", ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"Trimestre\", \"T\" & ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"SemNro\", ROUNDUP( MONTH( [Date] ) / 6, 0),",
                "    \"Semestre\", \"S\" & ROUNDUP( MONTH( [Date] ) / 6, 0),",
                "    \"Desvio Dia\", INT( [Date] ) - INT( Today() ),",
                "    \"SortMonthYear\", YEAR( [Date] ) * 100 + MONTH( [Date] ),",
                "    \"M-Y\" , UPPER( FORMAT( [Date], \"MMM\" ) ) & \"-\" & RIGHT(YEAR( [Date] ),2),",
                "    \"SortTrimYear\", YEAR( [Date] ) * 100 + ROUNDUP( MONTH( [Date] ) / 3, 0 ),",
                "    \"T-Y\" , \"T\" & ROUNDUP( MONTH( [Date] ) / 3, 0 ) & \"-\" & RIGHT(YEAR( [Date] ),2),",
                "    \"SortSemYear\", YEAR( [Date] ) * 100 + ROUNDUP( MONTH( [Date] ) / 6, 0),",
                "    \"S-Y\" , \"S\" & ROUNDUP( MONTH( [Date] ) / 6, 0) & \"-\" & RIGHT(YEAR( [Date] ),2),",
                "     \"Mes2\", UPPER( FORMAT( [Date], \"MMMM\" ) ))"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendario",
            "levels": [
              {
                "name": "Año",
                "ordinal": 0,
                "column": "Año"
              },
              {
                "name": "Mes",
                "ordinal": 1,
                "column": "Mes"
              }
            ]
          }
        ]
      },
      {
        "name": "dim Divisiones",
        "columns": [
          {
            "name": "Id_Divisiones",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id_Divisiones"
          },
          {
            "name": "BK_DIVISION",
            "dataType": "string",
            "sourceColumn": "BK_DIVISION"
          },
          {
            "name": "Descripcion Division",
            "dataType": "string",
            "sourceColumn": "Descripcion Division"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Divisiones = Source{[Schema=\"dim\",Item=\"Divisiones\"]}[Data]",
                "in",
                "    dim_Divisiones"
              ]
            }
          }
        ]
      },
      {
        "name": "Metricas visuales Costes",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Id",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": false,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Metricas Costes",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH('Metricas visuales Costes'[Id],",
              "1,\"Ingresos Totales\",",
              "2,\"M2\",",
              "3,\"Venta Neta\",",
              "4,\"Pr. Estándar\",",
              "5,\"Margen Industrial\",",
              "6,\"Margen Contribucion\",",
              "7,\"Margen Operativo\",",
              "8,\"Margen Neto\",",
              "9,\"Margen Final \"",
              ")"
            ],
            "sortByColumn": "Id"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{1,2,3,4,5,6,7,8,9}"
            }
          }
        ],
        "measures": [
          {
            "name": "Costes Real",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1, [Ingresos Totales],",
              "    2, [Total Cantidad M2 (Real)],",
              "    3, [Venta Neta],",
              "    4, [Pr. Estandar],",
              "    5, [ZTDOS51-- Margen Industrial],",
              "    6, [ZTDOS51-- Margen Contribucion],",
              "    7, [ZTDOS51-- Margen Operativo],",
              "    8, [ZTDOS51-- Margen Neto],",
              "    9, [ZTDOS51-- Margen Final]",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costes Plan",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes' [Id] ),",
              "    1, [Ingresos Totales Plan],",
              "    2, [Total Cantidad M2 (Plan)],",
              "    3, [Venta Neta Plan],",
              "    4, [Pr. Estándar Plan],",
              "    5, [Margen Industrial Plan],",
              "    6, [Margen Contribucion Plan],",
              "    7, [Margen Operativo Plan],",
              "    8, [Margen Neto Plan],",
              "    9, [Margen Final Plan]",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costes Real YTD",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1, CALCULATE( [Ingresos Totales], DATESYTD(  'dim Fechas'[Fecha] ) ),",
              "    2,",
              "        CALCULATE(",
              "            [Total Cantidad M2 (Real)], DATESYTD(  'dim Fechas'[Fecha] )",
              "        ),",
              "    3,",
              "        CALCULATE(",
              "            [Venta Neta],",
              "            DATESYTD(  'dim Fechas'[Fecha] )",
              "        ),",
              "    4, CALCULATE( [Pr. Estandar], DATESYTD(  'dim Fechas'[Fecha]) ),",
              "    5, CALCULATE( [ZTDOS51-- Margen Industrial], DATESYTD(  'dim Fechas'[Fecha] ) ),",
              "    6,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Contribucion], DATESYTD(  'dim Fechas'[Fecha] )",
              "        ),",
              "    7,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Operativo],",
              "            DATESYTD(  'dim Fechas'[Fecha] )",
              "        ),",
              "    8, CALCULATE( [ZTDOS51-- Margen Neto], DATESYTD(  'dim Fechas'[Fecha] ) ),",
              "    9,",
              "        CALCULATE( [ZTDOS51-- Margen Final], DATESYTD(  'dim Fechas'[Fecha] ) )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costes Plan YTD",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1,",
              "        CALCULATE( [Ingresos Totales Plan], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    2,",
              "        CALCULATE(",
              "            [Total Cantidad M2 (Plan)],",
              "            DATESYTD('dim Fechas'[Fecha] )",
              "        ),",
              "    3,",
              "        CALCULATE(",
              "            [Venta Neta Plan],",
              "            DATESYTD('dim Fechas'[Fecha] )",
              "        ),",
              "    4,",
              "        CALCULATE( [Pr. Estándar Plan], DATESYTD( 'dim Fechas'[Fecha] ) ),",
              "    5,",
              "        CALCULATE(",
              "            [Margen Industrial Plan],",
              "            DATESYTD('dim Fechas'[Fecha] )",
              "        ),",
              "    6,",
              "        CALCULATE(",
              "            [Margen Contribucion Plan],",
              "            DATESYTD( 'dim Fechas'[Fecha] )",
              "        ),",
              "    7,",
              "        CALCULATE(",
              "            [Margen Operativo Plan],",
              "            DATESYTD( 'dim Fechas'[Fecha] )",
              "        ),",
              "    8,",
              "        CALCULATE(",
              "            [Margen Neto Plan],",
              "            DATESYTD( 'dim Fechas'[Fecha] )",
              "        ),",
              "    9,",
              "        CALCULATE( [Margen Final Plan], DATESYTD( 'dim Fechas'[Fecha] ) )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Costes Real  SPLY",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1,",
              "        CALCULATE(",
              "            [Ingresos Totales],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])",
              "        ),",
              "    2,",
              "        CALCULATE(",
              "            [Total Cantidad M2 (Real)],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    3,",
              "        CALCULATE(",
              "            [Venta Neta],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    4,",
              "        CALCULATE(",
              "            [Pr. Estandar],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    5,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Industrial],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    6,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Contribucion],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    7,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Operativo],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    8,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Neto],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    9,",
              "        CALCULATE(",
              "            [ZTDOS51-- Margen Final],",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Diferencia Costes SPLY",
            "expression": "[Resultado Real]-[Real  SPLY]",
            "formatString": "#,0"
          },
          {
            "name": "% Real s / SPLY 1",
            "expression": "DIVIDE([Resultado Real],[Real  SPLY])-1",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Costes Plan vs Real",
            "expression": "[Costes Real] - [Costes Plan]",
            "formatString": "#,0"
          },
          {
            "name": "Costes Real  SPLY-YTD",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1,",
              "        CALCULATE(",
              "            CALCULATE([Ingresos Totales],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    2,",
              "        CALCULATE(",
              "            CALCULATE([Total Cantidad M2 (Real)],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    3,",
              "        CALCULATE(",
              "            CALCULATE([Venta Neta],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    4,",
              "        CALCULATE(",
              "            CALCULATE([Pr. Estandar],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    5,",
              "        CALCULATE(",
              "            CALCULATE([ZTDOS51-- Margen Industrial],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    6,",
              "        CALCULATE(",
              "            CALCULATE([ZTDOS51-- Margen Contribucion],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    7,",
              "        CALCULATE(",
              "            CALCULATE([ZTDOS51-- Margen Operativo],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    8,",
              "        CALCULATE(",
              "            CALCULATE([ZTDOS51-- Margen Neto],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        ),",
              "    9,",
              "        CALCULATE(",
              "            CALCULATE([ZTDOS51-- Margen Final],DATESYTD( 'dim Fechas'[Fecha])),",
              "            SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )",
              "        )",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "RANK Agrupado 1",
            "expression": [
              "VAR _Top = RANKX(ALL('dim Clientes'),[Diferencia Costes SPLY],,DESC,Dense)",
              "",
              "VAR _Down = RANKX(ALL('dim Clientes'),[Diferencia Costes SPLY],,ASC,Dense)",
              "",
              "RETURN",
              "IF(_Top<=10,\"TOP10\",IF(_Down<=10,\"DOWN10\",\"RESTO\"))"
            ]
          },
          {
            "name": "Ranking Ventas",
            "expression": [
              " RANKX(ALL('dim Clientes'),[Venta neta],,DESC,Dense)",
              "",
              ""
            ]
          },
          {
            "name": "ZCTAREDOS -- Costes Real",
            "expression": [
              "SWITCH(",
              "    MAX( 'Metricas visuales Costes'[Id] ),",
              "    1, [Ingresos Totales],",
              "    2, [Total Cantidad M2 (Real)],",
              "    3, [Venta Neta],",
              "    4, [Pr. Estandar],",
              "    5, [ZCTAREDOS2-- Margen Industrial],",
              "    6, [ZCTAREDOS2-- Margen Contribucion],",
              "    7, [ZCTAREDOS2-- Margen Operativo],",
              "    8, [ZCTAREDOS2-- Margen Neto],",
              "    9, [ZCTAREDOS2-- Margen Final]",
              ")"
            ]
          }
        ]
      },
      {
        "name": "Detalle Costes",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Sub_Id",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Desglose Coste",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "IF (",
              "    'Detalle Costes'[Sub_Id] = \"1.1\",",
              "    \"Precio Neto 5000\",",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"1.2\",",
              "    \"Ingresos\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"1.3\",",
              "    \"C. Transp. Teorico\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"1.4\",",
              "    \"Rec. Multidad\", ",
              "     IF ( 'Detalle Costes'[Sub_Id] = \"1.5\",",
              "    \"Abono Mala Calidad\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"3.1\",",
              "    \"Ingresos Totales\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"3.2\",",
              "    \"Descuentos Venta\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"3.3\",",
              "    \"Rappel\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"3.4\",",
              "   \"Abono Mala Calidad\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"3.5\",",
              "    \"Descuentos Roto Montadora\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"5.1\",",
              "    \"Pr. Estandar (Plan)\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"5.2\",",
              "    \"Desv. Product Costing\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"5.3\",",
              "    \"Desviacion Ordenes\", ",
              "    ",
              "     IF ( 'Detalle Costes'[Sub_Id] = \"6.1\",",
              "    \"Comision ventas\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.2\",",
              "    \"Transp. Total\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"6.3\",",
              "    \"Unic\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.4\",",
              "   \"Recargo Lidl\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.5\",",
              "    \"Chep Palet\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.6\",",
              "    \"Coste Palets\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.7\",",
              "    \"Coste Montaje\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"6.8\",",
              "    \"Seguro Caucion\", ",
              "     IF ( 'Detalle Costes'[Sub_Id] = \"6.9\",",
              "    \"Compra Troq/Cliches/Utiles\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.10\",",
              "    \"Gastos Montadora\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"6.11\",",
              "    \"Gastos Dir. Cogeneracion\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"6.12\",",
              "   \"Recorte\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"7.1\",",
              "    \"Estructura Comercial\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"7.2\",",
              "    \"Logistica Carga / Mtto\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"7.3\",",
              "    \"Estructura Oficinas\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"7.4\",",
              "    \"Estructura General\", ",
              "     IF ( 'Detalle Costes'[Sub_Id] = \"7.5\",",
              "    \"Gastos Cogeneracion\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"8.1\",",
              "    \"Ing Financieros\", ",
              "      IF ( 'Detalle Costes'[Sub_Id] = \"8.2\",",
              "    \"Gastos Financieros\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"8.3\",",
              "   \"Descuento Pronto Pago\", ",
              "    IF ( 'Detalle Costes'[Sub_Id] = \"9.1\",",
              "    \"Ing. Extraordin. Total\",",
              "    \" \" )",
              ")))))))))))))))))))))))))))))))))"
            ]
          },
          {
            "type": "calculated",
            "name": "Id",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "IF(LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"1\",",
              "    \"1\",",
              "    IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"3\",",
              "        \"3\",",
              "        IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"5\",",
              "            \"5\",",
              "             IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"6\",",
              "            \"6\",",
              "             IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"7\",",
              "            \"7\",",
              "             IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"8\",",
              "            \"8\",",
              "             IF( LEFT( 'Detalle Costes'[Sub_Id], 1 ) = \"9\",",
              "            \"9\",",
              "            \"Otros\"",
              "        )",
              "    )",
              ")",
              "))))"
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                " {\"1.1\",\"1.2\",\"1.3\",\"1.4\",\"1.5\",\"3.1\",\"3.2\",\"3.3\",\"3.4\",\"3.5\",\"5.1\",\"5.2\",\"5.3\",\"6.1\",\"6.2\",\"6.3\",\"6.4\",\"6.5\",\"6.6\",\"6.7\",\"6.8\",\"6.9\",\"6.10\",\"6.11\",\"6.12\",\"7.1\",\"7.2\",\"7.3\",\"7.4\",\"7.5\",\"8.1\",\"8.2\",\"8.3\",\"9.1\"}",
                " "
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Costes Visual",
            "expression": [
              "",
              "",
              "VAR _Costes =SWITCH(MAX('Detalle Costes'[Sub_Id]),",
              "    \"1.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Precio Neto 5000], BLANK()),",
              "    \"1.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Ingresos], BLANK()),",
              "    \"1.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ C.Transport. Teorico], BLANK()),",
              "    \"1.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Rec. Multsdad], BLANK()),",
              "    \"1.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Abono Mala Calidad], BLANK()),",
              "    \"3.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[Ingresos Totales], BLANK()),",
              "    \"3.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Descuento Ventas]*-1, BLANK()),",
              "    \"3.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Rappels], BLANK()),",
              "    \"3.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Abono Mala Calidad], BLANK()),",
              "    \"3.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Dtos Rotos Montadora]*-1, BLANK()),",
              "    \"3.6\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Abono Roto montad.], BLANK()),",
              "    \"5.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[Pr. Estandar], BLANK()),",
              "    \"5.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[Desv. Product Costing], BLANK()),",
              "    \"5.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[Desviacion Ordenes], BLANK()),",
              "    \"6.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Comision de Ventas]*-1, BLANK()),",
              "    \"6.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Transporte Total]*-1, BLANK()),",
              "    \"6.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Canon Unic]*-1, BLANK()),",
              "    \"6.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Coste Recargo Lidl]*-1, BLANK()),",
              "    \"6.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Coste Chep Palet]*-1, BLANK()),",
              "    \"6.6\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Coste Palets]*-1, BLANK()),",
              "    \"6.7\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Coste de Montaje]*-1, BLANK()),",
              "    \"6.8\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Seguro Caucion]*-1, BLANK()),",
              "    \"6.9\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Compra Troq/Cliches/Utiles]*-1, BLANK()),",
              "    \"6.10\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Gastos Montadora]*-1, BLANK()),",
              "    \"6.11\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Gastos Dir. Cogenerac.]*-1, BLANK()),",
              "    \"6.12\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Gastos Recorte]*-1, BLANK()),",
              "    \"7.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Estructura Comercial]*-1, BLANK()),",
              "    \"7.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Logistica Carga/Mtto]*-1, BLANK()),",
              "    \"7.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Estructura Oficinas]*-1, BLANK()),",
              "    \"7.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Estructura General]*-1, BLANK()),",
              "    \"7.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Gastos Cogeneracion]*-1, BLANK()),",
              "    \"8.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Ing. Financieros], BLANK()),",
              "    \"8.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Gastos Financieros]*-1, BLANK()),",
              "    \"8.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[€ Descuentos por pronto pago]*-1, BLANK()),",
              "    \"9.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),[Ing. Extraordin. Total], BLANK())",
              ")",
              "",
              "VAR _Costes2 = SWITCH(MAX('Detalle Costes'[Sub_Id]),",
              "    \"1.1\",[€ Precio Neto 5000],",
              "    \"1.2\",[€ Ingresos],",
              "    \"1.3\",[€ C.Transport. Teorico],",
              "    \"1.4\",[€ Rec. Multsdad], ",
              "    \"1.5\",[€ Abono Mala Calidad],",
              "    \"3.1\",[Ingresos Totales], ",
              "    \"3.2\",[€ Descuento Ventas]*-1, ",
              "    \"3.3\",[€ Rappels],",
              "    \"3.4\",[€ Abono Mala Calidad],",
              "    \"3.5\",[€ Dtos Rotos Montadora]*-1,",
              "    \"3.6\",[€ Abono Roto montad.], ",
              "    \"5.1\",[Pr. Estandar], ",
              "    \"5.2\",[Desv. Product Costing],",
              "    \"5.3\",[Desviacion Ordenes], ",
              "    \"6.1\",[€ Comision de Ventas]*-1,",
              "    \"6.2\",[€ Transporte Total]*-1, ",
              "    \"6.3\",[€ Canon Unic]*-1, ",
              "    \"6.4\",[€ Coste Recargo Lidl]*-1, ",
              "    \"6.5\",[€ Coste Chep Palet]*-1, ",
              "    \"6.6\",[€ Coste Palets]*-1, ",
              "    \"6.7\",[€ Coste de Montaje]*-1, ",
              "    \"6.8\",[€ Seguro Caucion]*-1, ",
              "    \"6.9\",[€ Compra Troq/Cliches/Utiles]*-1,",
              "    \"6.10\",[€ Gastos Montadora]*-1, ",
              "    \"6.11\",[€ Gastos Dir. Cogenerac.]*-1, ",
              "    \"6.12\",[€ Gastos Recorte]*-1, ",
              "    \"7.1\",[€ Estructura Comercial]*-1, ",
              "    \"7.2\",[€ Logistica Carga/Mtto]*-1, ",
              "    \"7.3\",[€ Estructura Oficinas]*-1, ",
              "    \"7.4\",[€ Estructura General]*-1, ",
              "    \"7.5\",[€ Gastos Cogeneracion]*-1, ",
              "    \"8.1\",[€ Ing. Financieros],",
              "    \"8.2\",[€ Gastos Financieros]*-1, ",
              "    \"8.3\",[€ Descuentos por pronto pago]*-1, ",
              "    \"9.1\",[Ing. Extraordin. Total] ",
              ")",
              "",
              "RETURN IF(ISFILTERED('Detalle Costes'[Sub_Id]),_Costes2)",
              "",
              "",
              "",
              ""
            ],
            "formatString": "#,0 \"€\";-#,0 \"€\";#,0 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"3082\" DisplayName=\"€ Spanish (Spain)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Costes Visual SPLY",
            "expression": [
              "SWITCH(MAX('Detalle Costes'[Sub_Id]),",
              "    \"1.1\",CALCULATE([€ Precio Neto 5000], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"1.2\",CALCULATE([€ Ingresos], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"1.3\",CALCULATE([€ C.Transport. Teorico], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"1.4\",CALCULATE([€ Rec. Multsdad], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"1.5\",CALCULATE([€ Abono Mala Calidad], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"3.1\",CALCULATE([Ingresos Totales], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"3.2\",CALCULATE([€ Descuento Ventas]*-1, SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"3.3\",CALCULATE([€ Rappels], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"3.4\",CALCULATE([€ Abono Mala Calidad], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"3.5\",CALCULATE([€ Dtos Rotos Montadora]*-1, SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"5.1\",CALCULATE([Pr. Estandar], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"5.2\",CALCULATE([Desv. Product Costing], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"5.3\",CALCULATE([Desviacion Ordenes], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"6.1\",CALCULATE([€ Comision de Ventas], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] )),",
              "    \"6.2\",CALCULATE([€ Transporte Total], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.3\",CALCULATE([€ Canon Unic], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.4\",CALCULATE([€ Coste Recargo Lidl], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] )),",
              "    \"6.5\",CALCULATE([€ Coste Chep Palet], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.6\",CALCULATE([€ Coste Palets], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"6.7\",CALCULATE([€ Coste de Montaje], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"6.8\",CALCULATE([€ Seguro Caucion], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.9\",CALCULATE([€ Compra Troq/Cliches/Utiles], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.10\",CALCULATE([€ Gastos Montadora], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"6.11\",CALCULATE([€ Gastos Dir. Cogenerac.], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"6.12\",CALCULATE([€ Gastos Recorte], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"7.1\",CALCULATE([€ Estructura Comercial], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"7.2\",CALCULATE([€ Logistica Carga/Mtto], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"7.3\",CALCULATE([€ Estructura Oficinas], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"7.4\",CALCULATE([€ Estructura General], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"7.5\",CALCULATE([€ Gastos Cogeneracion], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"8.1\",CALCULATE([€ Ing. Financieros], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"8.2\",CALCULATE([€ Gastos Financieros], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha] )),",
              "    \"8.3\",CALCULATE([€ Descuentos por pronto pago], SAMEPERIODLASTYEAR(  'dim Fechas'[Fecha])),",
              "    \"9.1\",CALCULATE([Ing. Extraordin. Total], SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha] ))",
              ")",
              ""
            ]
          },
          {
            "name": "% Costes Visual",
            "expression": [
              "SWITCH(MAX('Detalle Costes'[Sub_Id]),",
              "    \"1.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Precio Neto 5000],[Venta Neta])*100,BLANK()),",
              "    \"1.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Ingresos],[Venta Neta])*100,BLANK()),",
              "    \"1.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ C.Transport. Teorico],[Venta Neta])*100,BLANK()),",
              "    \"1.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Rec. Multsdad],[Venta Neta])*100,BLANK()),",
              "    \"1.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Abono Mala Calidad]*-1,[Venta Neta])*100,BLANK()),",
              "    \"3.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([Ingresos Totales],[Ingresos Totales])*100,BLANK()),",
              "    \"3.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Descuento Ventas],[Ingresos Totales])*100,BLANK()),",
              "    \"3.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Rappels]*-1,[Ingresos Totales])*100,BLANK()),",
              "    \"3.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Abono Mala Calidad]*-1,[Ingresos Totales])*100,BLANK()),",
              "    \"3.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Dtos Rotos Montadora],[Ingresos Totales])*100,BLANK()),",
              "    \"3.6\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Abono Roto montad.]*-1,[Venta Neta])*100,BLANK()),",
              "    \"5.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([Pr. Estandar],[Venta Neta])*100,BLANK()),",
              "    \"5.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([Desv. Product Costing],[Venta Neta])*100,BLANK()),",
              "    \"5.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([Desviacion Ordenes],[Venta Neta])*100,BLANK()),",
              "    \"6.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Comision de Ventas],[Venta Neta])*100,BLANK()),",
              "    \"6.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Transporte Total],[Venta Neta])*100,BLANK()),",
              "    \"6.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Canon Unic],[Venta Neta])*100,BLANK()),",
              "    \"6.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Coste Recargo Lidl],[Venta Neta])*100,BLANK()),",
              "    \"6.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Coste Chep Palet],[Venta Neta])*100,BLANK()),",
              "    \"6.6\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Coste Palets],[Venta Neta])*100,BLANK()),",
              "    \"6.7\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Coste de Montaje],[Venta Neta])*100,BLANK()),",
              "    \"6.8\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Seguro Caucion],[Venta Neta])*100,BLANK()),",
              "    \"6.9\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Compra Troq/Cliches/Utiles],[Venta Neta])*100,BLANK()),",
              "    \"6.10\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Gastos Montadora],[Venta Neta])*100,BLANK()),",
              "    \"6.11\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Gastos Dir. Cogenerac.],[Venta Neta])*100,BLANK()),",
              "    \"6.12\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Gastos Recorte],[Venta Neta])*100,BLANK()),",
              "    \"7.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Estructura Comercial],[Venta Neta])*100,BLANK()),",
              "    \"7.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Logistica Carga/Mtto],[Venta Neta])*100,BLANK()),",
              "    \"7.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Estructura Oficinas],[Venta Neta])*100,BLANK()),",
              "    \"7.4\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Estructura General],[Venta Neta])*100,BLANK()),",
              "    \"7.5\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Gastos Cogeneracion],[Venta Neta])*100,BLANK()),",
              "    \"8.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Ing. Financieros],[Venta Neta])*100,BLANK()),",
              "    \"8.2\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Gastos Financieros],[Venta Neta])*100,BLANK()),",
              "    \"8.3\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([€ Descuentos por pronto pago],[Venta Neta])*100,BLANK()),",
              "    \"9.1\",IF(ISFILTERED('Detalle Costes'[Sub_Id]),DIVIDE([Ing. Extraordin. Total],[Venta Neta])*100,BLANK())",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Aviso Medida Seleccionada",
            "expression": [
              "IF(",
              "    NOT ( ISFILTERED( 'Detalle Costes'[Sub_Id] ) ),",
              "    \"Seleccionar de la Gráfica Desglose Costes\",",
              "    \"\"",
              ")"
            ]
          }
        ]
      },
      {
        "name": "Detalle Costes 2",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Sub_Id",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Desglose Coste",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "IF (",
              "    'Detalle Costes 2'[Sub_Id] = \"5.1.1\",",
              "    \"Consumo Papeles\",",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.2\",",
              "    \"Consumo Pdtos Ondulados\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.3\",",
              "    \"Consumo Tintas\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.4\",",
              "    \"Consumo Palets\", ",
              "     IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.5\",",
              "    \"Consumo Aprov. Varios\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.6\",",
              "    \"Actividad Externa\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.7\",",
              "    \"Costes Horas Maquinaria\", ",
              "      IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.8\",",
              "    \"Coste MOD\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.9\",",
              "   \"Coste Estructura\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.1.10\",",
              "    \"Coste Montaje\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.1\",",
              "    \"Desv. Precio Input\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.2\",",
              "    \"Desvac. Estructura\", ",
              "      IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.3\",",
              "    \"Desv. Ctd a Emplear\", ",
              "     IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.4\",",
              "    \"Desv. Restante Input\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.5\",",
              "    \"Desv. Precio Imputac.\", ",
              "      IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.6\",",
              "    \"Desv. Costes Fijos\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.7\",",
              "   \"Desv. Ctd. Imputacion\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.8\",",
              "    \"Desviaion Restante\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.9\",",
              "    \"Desv. Rechazo\", ",
              "    IF ( 'Detalle Costes 2'[Sub_Id] = \"5.3.10\",",
              "    \"Desv. Precio Mixto\", ",
              "     \" \" )",
              ")))))))))))))))))))"
            ],
            "sortByColumn": "Sub_Id"
          },
          {
            "type": "calculated",
            "name": "Id",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "5"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " {\"5.1.1\",\"5.1.2\",\"5.1.3\",\"5.1.4\",\"5.1.5\",\"5.1.6\",\"5.1.7\",\"5.1.8\",\"5.1.9\",\"5.1.10\",\"5.3.1\",\"5.3.2\",\"5.3.3\",\"5.3.4\",\"5.3.5\",\"5.3.6\",\"5.3.7\",\"5.3.8\",\"5.3.9\",\"5.3.10\"}"
            }
          }
        ],
        "measures": [
          {
            "name": "Desglose Costes Visual",
            "expression": [
              "SWITCH(MAX('Detalle Costes 2'[Sub_Id]),",
              "    \"5.1.1\",[* Consumo Papeles],",
              "    \"5.1.2\",[* Consumo Pdtos Ondulados],",
              "    \"5.1.3\",[* Consumo Tintas],",
              "    \"5.1.4\",[* Consumo Palets],",
              "    \"5.1.5\",[* Consumo Aprov. Varios],",
              "    \"5.1.6\",[* Actividad Externa],",
              "    \"5.1.7\",[* Coste Horas maquina],",
              "    \"5.1.8\",[* Coste MOD],",
              "    \"5.1.9\",[* Coste Estructura],",
              "    \"5.1.10\",[* Coste Montaje],",
              "    \"5.3.1\",[** Desv. Precio input],",
              "    \"5.3.2\",[** Desviac. Estructura],",
              "    \"5.3.3\",[** Desv. Ctd. a emplear],",
              "    \"5.3.4\",[** Desv. Restante input],",
              "    \"5.3.5\",[** Desv. Precio imputac],",
              "    \"5.3.6\",[** Desv. Costes Fijos],",
              "    \"5.3.7\",[** Desv. Ctd imputacion],",
              "    \"5.3.8\",[** Desviacion Restante],",
              "    \"5.3.9\",[** Desv. Rechazo],",
              "    \"5.3.10\",[** Desv. Precio Mixto]",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "% Desglose Costes Visual",
            "expression": [
              "SWITCH(MAX('Detalle Costes 2'[Sub_Id]),",
              "    \"5.1.1\",DIVIDE([* Consumo Papeles],[Venta Neta])*100,",
              "    \"5.1.2\",DIVIDE([* Consumo Pdtos Ondulados],[Venta Neta])*100,",
              "    \"5.1.3\",DIVIDE([* Consumo Tintas],[Venta Neta])*100,",
              "    \"5.1.4\",DIVIDE([* Consumo Palets],[Venta Neta])*100,",
              "    \"5.1.5\",DIVIDE([* Consumo Aprov. Varios],[Venta Neta])*100,",
              "    \"5.1.6\",DIVIDE([* Actividad Externa],[Venta Neta])*100,",
              "    \"5.1.7\",DIVIDE([* Coste Horas maquina],[Venta Neta])*100,",
              "    \"5.1.8\",DIVIDE([* Coste MOD],[Venta Neta])*100,",
              "    \"5.1.9\",DIVIDE([* Coste Estructura],[Venta Neta])*100,",
              "    \"5.1.10\",DIVIDE([* Coste Montaje],[Venta Neta])*100,",
              "    \"5.3.1\",DIVIDE([** Desv. Precio input],[Venta Neta])*100,",
              "    \"5.3.2\",DIVIDE([** Desviac. Estructura],[Venta Neta])*100,",
              "    \"5.3.3\",DIVIDE([** Desv. Ctd. a emplear],[Venta Neta])*100,",
              "    \"5.3.4\",DIVIDE([** Desv. Restante input],[Venta Neta])*100,",
              "    \"5.3.5\",DIVIDE([** Desv. Precio imputac],[Venta Neta])*100,",
              "    \"5.3.6\",DIVIDE([** Desv. Costes Fijos],[Venta Neta])*100,",
              "    \"5.3.7\",DIVIDE([** Desv. Ctd imputacion],[Venta Neta])*100,",
              "    \"5.3.8\",DIVIDE([** Desviacion Restante],[Venta Neta])*100,",
              "    \"5.3.9\",DIVIDE([** Desv. Rechazo],[Venta Neta])*100,",
              "    \"5.3.10\",DIVIDE([** Desv. Precio Mixto],[Venta Neta])*100",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Desglose Costes Visual SPLY",
            "expression": [
              "SWITCH(MAX('Detalle Costes 2'[Sub_Id]),",
              "    \"5.1.1\",CALCULATE([* Consumo Papeles],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.2\",CALCULATE([* Consumo Pdtos Ondulados],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.3\",CALCULATE([* Consumo Tintas],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.4\",CALCULATE([* Consumo Palets],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.5\",CALCULATE([* Consumo Aprov. Varios],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.6\",CALCULATE([* Actividad Externa],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.7\",CALCULATE([* Coste Horas maquina],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.8\",CALCULATE([* Coste MOD],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.9\",CALCULATE([* Coste Estructura],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.1.10\",CALCULATE([* Coste Montaje],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.1\",CALCULATE([** Desv. Precio input],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.2\",CALCULATE([** Desviac. Estructura],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.3\",CALCULATE([** Desv. Ctd. a emplear],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.4\",CALCULATE([** Desv. Restante input],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.5\",CALCULATE([** Desv. Precio imputac],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.6\",CALCULATE([** Desv. Costes Fijos],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.7\",CALCULATE([** Desv. Ctd imputacion],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.8\",CALCULATE([** Desviacion Restante],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.9\",CALCULATE([** Desv. Rechazo],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha])),",
              "    \"5.3.10\",CALCULATE([** Desv. Precio Mixto],SAMEPERIODLASTYEAR( 'dim Fechas'[Fecha]))",
              ")"
            ]
          },
          {
            "name": "Titulo Grafico Historico Costes",
            "expression": [
              "VAR _Metricas =",
              "    SELECTEDVALUE( 'Metricas visuales Costes'[Metricas Costes] )",
              "RETURN",
              "    _Metricas & \" por AÑOS\""
            ]
          },
          {
            "name": "Titulo Grafico Historico Costes 1",
            "expression": [
              "VAR _Metricas =",
              "    SELECTEDVALUE( 'Detalle Costes'[Desglose Coste] )",
              "RETURN",
              "    IF(",
              "        _Metricas = \"\",",
              "        \"Evolución Anual Costes\",",
              "        _Metricas & \" por AÑOS\"",
              "    )"
            ]
          },
          {
            "name": "Titulo Grafico Ratio Costes 1",
            "expression": [
              "VAR _Metricas =",
              "    SELECTEDVALUE( 'Detalle Costes'[Desglose Coste] )",
              "VAR _MetricasVis =",
              "    SELECTEDVALUE( 'Metricas visuales Costes'[Metricas Costes] )",
              "RETURN",
              "    IF(",
              "        _MetricasVis = \"Venta Neta\" && _Metricas = \"\",",
              "        \"Evolución s/Ingresos Totales\",",
              "        IF(",
              "            _MetricasVis <> \"Venta Neta\" && _Metricas = \"\",",
              "            \"Evolucion s/Venta Neta\",",
              "            IF(",
              "                _MetricasVis <> \"Venta Neta\" && _Metricas <> \"\",",
              "                \"% \" & _Metricas & \" s/Venta Neta\",",
              "                \"% \" & _Metricas & \" s/Ingresos Totales\"",
              "            )",
              "        )",
              "    )"
            ]
          },
          {
            "name": "Titulo Grafico Historico Costes 2",
            "expression": [
              "VAR _Metricas =",
              "    SELECTEDVALUE( 'Metricas visuales Costes'[Metricas Costes] )",
              "VAR _Year = SELECTEDVALUE( 'dim Fechas'[Año] )",
              "RETURN",
              "    \"Historico \" & _Metricas & \" en \" & _Year"
            ]
          }
        ]
      },
      {
        "name": "SeleccionClientes",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Id_Clientes",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Id_Clientes]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Nombre",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Nombre]"
          },
          {
            "type": "calculated",
            "name": "Activo/Inactivo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(SeleccionClientes[Id_Clientes],",
              "5335,0,1)"
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "",
                "VAR Clientes = SELECTCOLUMNS('dim Clientes',\"Id_Clientes\",'dim Clientes'[Id_Clientes],\"Nombre\",'dim Clientes'[Nombre])",
                "",
                "VAR _Resto = UNION(ROW(\"Id_Clientes\",10000000,\"Nombre\",\"RESTO -\"),ROW(\"Id_Clientes\",10000001,\"Nombre\",\"RESTO +\"))",
                "",
                "VAR _Totales = UNION(ROW(\"Id_Clientes\",20000000,\"Nombre\",\"SPLY\"),ROW(\"Id_Clientes\",20000001,\"Nombre\",\"PLAN\"))",
                "",
                "",
                "VAR Result =UNION( UNION(Clientes,_Resto),_Totales)",
                "",
                "",
                "RETURN ",
                "",
                "Result"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Rank PvsR + Resto",
            "expression": [
              "",
              "",
              "VAR _NumTopClientes = 7",
              "",
              "/****** RANKING TOP N *******/",
              "",
              "VAR _TopN =",
              "  TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif Plan vs Real],SeleccionClientes[Activo/Inactivo]=1)",
              "    )",
              "VAR _DifTopN =",
              "    CALCULATE (",
              "        [Dif Plan vs Real],",
              "        KEEPFILTERS ( _TopN )",
              "    )",
              "    ",
              " VAR RestoPositivos = CALCULATE([Dif Plan vs Real] ,FILTER(ALLSELECTED(SeleccionClientes),[Dif Plan vs Real]>0))- CALCULATE([Dif Plan vs Real],_TopN)",
              " ",
              "    ",
              "/****** RANKING DOWN N *******/",
              "",
              "VAR _DownN =",
              "    TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif Plan vs Real],SeleccionClientes[Activo/Inactivo]=1), ASC",
              "    )",
              "VAR _DifDownN =",
              "    CALCULATE (",
              "        [Dif Plan vs Real],",
              "        KEEPFILTERS ( _DownN )",
              "    )",
              "",
              "VAR RestoNegativos = CALCULATE( [Dif Plan vs Real],FILTER(ALLSELECTED(SeleccionClientes),[Dif Plan vs Real]<0))- CALCULATE([Dif Plan vs Real],_DownN)",
              "",
              "VAR SeleccionPos = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000001",
              "VAR SeleccionNeg = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000000",
              "",
              "",
              "VAR Result =   IF(SeleccionPos, RestoPositivos,IF(SeleccionNeg,RestoNegativos,_DifTopN + _DifDownN))",
              "    ",
              "RETURN",
              "Result    "
            ],
            "formatString": "#,0"
          },
          {
            "name": "Rank RvsSPLY + Resto",
            "expression": [
              "",
              "",
              "VAR _NumTopClientes = 7",
              "",
              "/****** RANKING TOP N *******/",
              "",
              "VAR _TopN =",
              "  TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif SPLY],SeleccionClientes[Activo/Inactivo]=1)",
              "    )",
              "VAR _DifTopN =",
              "    CALCULATE (",
              "        [Dif SPLY],",
              "        KEEPFILTERS ( _TopN )",
              "    )",
              "    ",
              " VAR RestoPositivos = CALCULATE([Dif SPLY] ,FILTER(ALLSELECTED(SeleccionClientes),[Dif SPLY]>0))- CALCULATE([Dif SPLY],_TopN)",
              " ",
              "    ",
              "/****** RANKING DOWN N *******/",
              "",
              "VAR _DownN =",
              "    TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif SPLY],SeleccionClientes[Activo/Inactivo]=1), ASC",
              "    )",
              "VAR _DifDownN =",
              "    CALCULATE (",
              "        [Dif SPLY],",
              "        KEEPFILTERS ( _DownN )",
              "    )",
              "",
              "VAR RestoNegativos = CALCULATE( [Dif SPLY],FILTER(ALLSELECTED(SeleccionClientes),[Dif SPLY]<0))- CALCULATE([Dif SPLY],_DownN)",
              "VAR SeleccionPos = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000001",
              "VAR SeleccionNeg = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000000",
              "",
              "",
              "VAR Result =   IF(SeleccionPos, RestoPositivos,IF(SeleccionNeg,RestoNegativos,_DifTopN + _DifDownN))",
              "    ",
              "RETURN",
              "Result    "
            ],
            "formatString": "#,0"
          },
          {
            "name": "Copy of Rank PvsR + Resto",
            "expression": [
              "",
              "",
              "VAR _NumTopClientes = 7",
              "",
              "/****** RANKING TOP N *******/",
              "",
              "VAR _TopN =",
              "  TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif Plan vs Real],SeleccionClientes[Activo/Inactivo]=1)",
              "    )",
              "VAR _DifTopN =",
              "    CALCULATE (",
              "        [Dif Plan vs Real],",
              "        KEEPFILTERS ( _TopN )",
              "    )",
              "    ",
              " VAR RestoPositivos = CALCULATE([Dif Plan vs Real] ,FILTER(ALLSELECTED(SeleccionClientes),[Dif Plan vs Real]>0))- CALCULATE([Dif Plan vs Real],_TopN)",
              " ",
              "    ",
              "/****** RANKING DOWN N *******/",
              "",
              "VAR _DownN =",
              "    TOPN (",
              "        _NumTopClientes,",
              "        ALLSELECTED ( SeleccionClientes[Nombre] ),",
              "        CALCULATE([Dif Plan vs Real],SeleccionClientes[Activo/Inactivo]=1), ASC",
              "    )",
              "VAR _DifDownN =",
              "    CALCULATE (",
              "        [Dif Plan vs Real],",
              "        KEEPFILTERS ( _DownN )",
              "    )",
              "",
              "VAR RestoNegativos = CALCULATE( [Dif Plan vs Real],FILTER(ALLSELECTED(SeleccionClientes),[Dif Plan vs Real]<0))- CALCULATE([Dif Plan vs Real],_DownN)",
              "",
              "",
              "VAR PLAN = CALCULATE([Resultado Plan],ALLSELECTED(SeleccionClientes))",
              "VAR REAL = CALCULATE([Resultado Real],ALLSELECTED(SeleccionClientes))",
              "",
              "VAR SeleccionPos = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000001     /* RESTO +  */",
              "VAR SeleccionNeg = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=10000000     /* RESTO -  */",
              "VAR SeleccionPLAN = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=20000001    /* TOTAL PLAN */",
              "VAR SeleccionSPLY = SELECTEDVALUE(SeleccionClientes[Id_Clientes])=20000000    /*  TOTAL SPLY  */",
              "",
              "",
              "",
              "VAR Result =   IF(SeleccionPLAN,PLAN,IF(SeleccionSPLY,REAL,IF(SeleccionPos,RestoPositivos,IF(SeleccionNeg,RestoNegativos,_DifTopN + _DifDownN))))",
              "    ",
              "RETURN",
              "Result    "
            ],
            "formatString": "#,0"
          },
          {
            "name": "% Objetivo PvsR",
            "expression": "DIVIDE([Resultado Real],[Resultado Plan])-1"
          },
          {
            "name": "Titulo Dpto Comercial SPLY",
            "expression": [
              " ",
              "VAR _Metricas = SWITCH(SELECTEDVALUE('Metricas visuales'[Id]),1,\"Euros\",2,\"M2\",\"Otros\")",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sector = SELECTEDVALUE('dim Sectores'[Descripcion Sector])",
              "",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT (ISBLANK(_FirstMonth=_LastMonth)),  \"Informe Resultado AÑO ANTERIOR en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &  _Month & \" de \" & _Year,",
              "        NOT (ISBLANK( _FirstMonth<>_LastMonth)),   \"Informe Resultado AÑO ANTERIOR en \" & _Metricas & \" del Sector \"  & _Sector & \" en\" & \"[ Varios Meses ]\" & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Month ) ),  \"Informe Resultado AÑO ANTERIOR en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &_Month & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Year ) ),  \"Informe Resultado AÑO ANTERIOR en \" & _Metricas & \" del Sector \"  & _Sector & \" en \" & _Year,",
              "        \"Informe Resultado AÑO ANTERIOR en \" & _Metricas & \" del Sector \" & _Sector ",
              "    )",
              "    ",
              "RETURN",
              "",
              "_Result"
            ]
          },
          {
            "name": "Titulo Dpto Comercial PLAN",
            "expression": [
              " ",
              "VAR _Metricas = SWITCH(SELECTEDVALUE('Metricas visuales'[Id]),1,\"Euros\",2,\"M2\",\"Otros\")",
              "VAR _Year = SELECTEDVALUE ( 'dim Fechas'[Año] )",
              "VAR _Month = SELECTEDVALUE ( 'dim Fechas'[Mes] )",
              "VAR _FirstMonth = MONTH(MIN('dim Fechas'[Fecha]))",
              "VAR _LastMonth = MONTH(MAX('dim Fechas'[Fecha]))",
              "VAR _Sector = SELECTEDVALUE('dim Sectores'[Descripcion Sector])",
              "",
              "",
              "VAR _Result =",
              "    SWITCH (",
              "        TRUE (),",
              "        NOT (ISBLANK(_FirstMonth=_LastMonth)),  \"Informe Resultado PLAN en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &  _Month & \" de \" & _Year,",
              "        NOT (ISBLANK( _FirstMonth<>_LastMonth)),   \"Informe Resultado PLAN en \" & _Metricas & \" del Sector \"  & _Sector & \" en\" & \"[ Varios Meses ]\" & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Month ) ),  \"Informe Resultado PLAN en \" & _Metricas & \" del Sector \" & _Sector & \" en \" &_Month & \" de \" & _Year ,",
              "        NOT ( ISBLANK ( _Year ) ),  \"Informe Resultado PLAN en \" & _Metricas & \" del Sector \"  & _Sector & \" en \" & _Year,",
              "        \"Informe Resultado PLAN en \" & _Metricas & \" del Sector \" & _Sector ",
              "    )",
              "    ",
              "RETURN",
              "",
              "_Result"
            ]
          }
        ]
      },
      {
        "name": "dim Fechas",
        "columns": [
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha"
          },
          {
            "name": "Año",
            "dataType": "int64",
            "sourceColumn": "Año",
            "summarizeBy": "none"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "sourceColumn": "Mes",
            "sortByColumn": "MesNro"
          },
          {
            "name": "MesNro",
            "dataType": "int64",
            "sourceColumn": "MesNro"
          },
          {
            "name": "DiaNro",
            "dataType": "int64",
            "sourceColumn": "DiaNro"
          },
          {
            "name": "SemanaNro",
            "dataType": "int64",
            "sourceColumn": "SemanaNro"
          },
          {
            "name": "Semana",
            "dataType": "string",
            "sourceColumn": "Semana"
          },
          {
            "name": "Fin de Semana",
            "dataType": "string",
            "sourceColumn": "Fin de Semana"
          },
          {
            "name": "DiaSemana",
            "dataType": "int64",
            "sourceColumn": "DiaSemana"
          },
          {
            "name": "Nombre Dia",
            "dataType": "string",
            "sourceColumn": "Nombre Dia"
          },
          {
            "name": "TrimNro",
            "dataType": "int64",
            "sourceColumn": "TrimNro"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "sourceColumn": "Trimestre"
          },
          {
            "name": "SemestreNro",
            "dataType": "int64",
            "sourceColumn": "SemestreNro"
          },
          {
            "name": "Semestre",
            "dataType": "string",
            "sourceColumn": "Semestre"
          },
          {
            "name": "AñoMes",
            "dataType": "int64",
            "sourceColumn": "AñoMes"
          },
          {
            "name": "MesAño",
            "dataType": "string",
            "sourceColumn": "MesAño"
          },
          {
            "name": "AñoTrim",
            "dataType": "int64",
            "sourceColumn": "AñoTrim"
          },
          {
            "name": "TrimAño",
            "dataType": "string",
            "sourceColumn": "TrimAño"
          },
          {
            "name": "AñoSem",
            "dataType": "int64",
            "sourceColumn": "AñoSem"
          },
          {
            "name": "SemAño",
            "dataType": "string",
            "sourceColumn": "SemAño"
          },
          {
            "name": "AñoSemana",
            "dataType": "int64",
            "sourceColumn": "AñoSemana"
          },
          {
            "name": "SemanaAño",
            "dataType": "string",
            "sourceColumn": "SemanaAño"
          },
          {
            "name": "Fecha Cierre Calidad",
            "dataType": "dateTime",
            "sourceColumn": "Fecha Cierre Calidad"
          },
          {
            "name": "Dia Cierre Calidad",
            "dataType": "int64",
            "sourceColumn": "Dia Cierre Calidad"
          },
          {
            "name": "Mes 2",
            "dataType": "string",
            "sourceColumn": "Mes",
            "sortByColumn": "MesNro"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Fechas = Source{[Schema=\"dim\",Item=\"Fechas\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dim_Fechas,{{\"Año\", Int64.Type}, {\"MesNro\", Int64.Type}, {\"DiaNro\", Int64.Type}, {\"SemanaNro\", Int64.Type}, {\"DiaSemana\", Int64.Type}, {\"TrimNro\", Int64.Type}, {\"SemestreNro\", Int64.Type}, {\"AñoMes\", Int64.Type}, {\"AñoTrim\", Int64.Type}, {\"AñoSem\", Int64.Type}, {\"AñoSemana\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Ramo_Industrial",
        "columns": [
          {
            "name": "ID_Ramo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID_Ramo",
            "formatString": "#,##0"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_RAMOINDUSTRIAL",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BK_RAMOINDUSTRIAL"
          },
          {
            "name": "Descripcion Ramo",
            "dataType": "string",
            "sourceColumn": "Descripcion Ramo",
            "sortByColumn": "BK_RAMOINDUSTRIAL"
          },
          {
            "name": "Nivel2",
            "dataType": "string",
            "sourceColumn": "Nivel2"
          },
          {
            "name": "DescripcionNivel2",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel2"
          },
          {
            "name": "Nivel3",
            "dataType": "string",
            "sourceColumn": "Nivel3"
          },
          {
            "name": "DescripcionNivel3",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel3"
          },
          {
            "name": "Nivel4",
            "dataType": "string",
            "sourceColumn": "Nivel4"
          },
          {
            "name": "DescripcionNivel4",
            "dataType": "string",
            "sourceColumn": "DescripcionNivel4"
          }
        ],
        "partitions": [
          {
            "name": "Ramo_Industrial",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    Data = Source{[Schema=\"dim\",Item=\"Ramo_Industrial\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(Data,\"\",null,Replacer.ReplaceValue,{\"Nivel2\", \"DescripcionNivel2\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Ramo Industrial",
            "levels": [
              {
                "name": "DescripcionNivel4",
                "ordinal": 0,
                "column": "DescripcionNivel4"
              },
              {
                "name": "DescripcionNivel3",
                "ordinal": 1,
                "column": "DescripcionNivel3"
              },
              {
                "name": "DescripcionNivel2",
                "ordinal": 2,
                "column": "DescripcionNivel2"
              },
              {
                "name": "Descripcion Ramo",
                "ordinal": 3,
                "column": "Descripcion Ramo"
              }
            ]
          }
        ]
      },
      {
        "name": "Materiales",
        "columns": [
          {
            "name": "Id_Materiales",
            "dataType": "int64",
            "sourceColumn": "Id_Materiales"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_MATERIAL",
            "dataType": "string",
            "sourceColumn": "BK_MATERIAL"
          },
          {
            "name": "BK_CENTRO",
            "dataType": "string",
            "sourceColumn": "BK_CENTRO"
          },
          {
            "name": "BK_ALMACEN",
            "dataType": "string",
            "sourceColumn": "BK_ALMACEN"
          },
          {
            "name": "BK_TipoMaterial",
            "dataType": "string",
            "sourceColumn": "BK_TipoMaterial"
          },
          {
            "name": "BK_Ramo",
            "dataType": "string",
            "sourceColumn": "BK_Ramo"
          },
          {
            "name": "BK_GrupoArticulos",
            "dataType": "string",
            "sourceColumn": "BK_GrupoArticulos"
          },
          {
            "name": "Nombre Material",
            "dataType": "string",
            "sourceColumn": "Nombre Material"
          },
          {
            "name": "UM Material",
            "dataType": "string",
            "sourceColumn": "UM Material"
          },
          {
            "name": "Grupo Articulos",
            "dataType": "string",
            "sourceColumn": "Grupo Articulos"
          },
          {
            "name": "Nombre Grupo",
            "dataType": "string",
            "sourceColumn": "Nombre Grupo"
          },
          {
            "name": "Jerarquía",
            "dataType": "string",
            "sourceColumn": "Jerarquía"
          },
          {
            "name": "Familia",
            "dataType": "string",
            "sourceColumn": "Familia"
          },
          {
            "name": "SubFamilia1",
            "dataType": "string",
            "sourceColumn": "SubFamilia1"
          },
          {
            "name": "Calidad",
            "dataType": "string",
            "sourceColumn": "Calidad"
          },
          {
            "name": "Digital",
            "dataType": "string",
            "sourceColumn": "Digital"
          },
          {
            "name": "AltaCalidad",
            "dataType": "string",
            "sourceColumn": "AltaCalidad"
          }
        ],
        "partitions": [
          {
            "name": "Materiales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    Data = Source{[Schema=\"dim\",Item=\"Materiales\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Provisional_Atributos_Materiales_Costes",
        "columns": [
          {
            "name": "Id_Atributos_Materiales_PROVISIONAL",
            "dataType": "int64",
            "sourceColumn": "Id_Atributos_Materiales_PROVISIONAL"
          },
          {
            "name": "Grupo de materiales 1",
            "dataType": "string",
            "sourceColumn": "Grupo de materiales 1"
          },
          {
            "name": "Grupo de material 2",
            "dataType": "string",
            "sourceColumn": "Grupo de material 2"
          },
          {
            "name": "Descripcion Familia",
            "dataType": "string",
            "sourceColumn": "Descripcion Familia"
          },
          {
            "name": "Descripcion SubFamilia",
            "dataType": "string",
            "sourceColumn": "Descripcion SubFamilia"
          },
          {
            "name": "Agrupacion Familia",
            "dataType": "string",
            "sourceColumn": "Agrupacion Familia",
            "sortByColumn": "Orden Agrupacion Familia"
          },
          {
            "name": "Orden Agrupacion Familia",
            "dataType": "int64",
            "sourceColumn": "Orden Agrupacion Familia"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Provisional_Atributos_Materiales_Costes = Source{[Schema=\"dim\",Item=\"Provisional_Atributos_Materiales_Costes\"]}[Data]",
                "in",
                "    dim_Provisional_Atributos_Materiales_Costes"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Personal",
        "columns": [
          {
            "name": "Id_Personal",
            "dataType": "int64",
            "sourceColumn": "Id_Personal"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_PERSONAL",
            "dataType": "string",
            "sourceColumn": "BK_PERSONAL"
          },
          {
            "name": "Apellidos Nombre",
            "dataType": "string",
            "sourceColumn": "Apellidos Nombre"
          },
          {
            "name": "Nombre Completo",
            "dataType": "string",
            "sourceColumn": "Nombre Completo",
            "sortByColumn": "BK_PERSONAL"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Personal = Source{[Schema=\"dim\",Item=\"Personal\"]}[Data]",
                "in",
                "    dim_Personal"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Proveedores",
        "columns": [
          {
            "name": "Id_Proveedores",
            "dataType": "int64",
            "sourceColumn": "Id_Proveedores"
          },
          {
            "name": "BK_MANDT",
            "dataType": "string",
            "sourceColumn": "BK_MANDT"
          },
          {
            "name": "BK_PROVEEDOR",
            "dataType": "string",
            "sourceColumn": "BK_PROVEEDOR"
          },
          {
            "name": "Nombre",
            "dataType": "string",
            "sourceColumn": "Nombre"
          },
          {
            "name": "Poblacion",
            "dataType": "string",
            "sourceColumn": "Poblacion"
          },
          {
            "name": "Zona Transporte",
            "dataType": "string",
            "sourceColumn": "Zona Transporte"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/POWERBI\\DWHPOWERBI;DWH_CLP_TEST\",",
                "    dim_Proveedores = Source{[Schema=\"dim\",Item=\"Proveedores\"]}[Data]",
                "in",
                "    dim_Proveedores"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "ab7ecc99-bf37-4008-9261-a7619d00456f",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Clientes",
        "toTable": "dim Clientes",
        "toColumn": "Id_Clientes"
      },
      {
        "name": "d6229f84-c6e8-4801-88d6-1f9da9e8d498",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Organizacion_Ventas",
        "toTable": "dim Organizacion_Ventas",
        "toColumn": "Id_Organizacion_Ventas"
      },
      {
        "name": "7fdd29da-f149-4e48-887b-f447ae6aac4e",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Zona_Ventas",
        "toTable": "dim Zona_Ventas",
        "toColumn": "ID Geografia"
      },
      {
        "name": "1838f5cd-736a-4c3f-add8-65fd7918e64f",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Costes",
        "toTable": "dim Atributos_Costes",
        "toColumn": "Id_Costes"
      },
      {
        "name": "17f151c2-2f40-483a-9300-23f91643a1dd",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Materiales",
        "toTable": "dim Material",
        "toColumn": "Id_Material"
      },
      {
        "name": "9535e0d9-f1c3-4db3-b6cb-ff90ca5f06f4",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Centros",
        "toTable": "dim Centro",
        "toColumn": "Id_Centro"
      },
      {
        "name": "4f2d6ff6-9de9-417d-928c-813f7e262401",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Costes",
        "toTable": "dim Atributos_Costes",
        "toColumn": "Id_Costes"
      },
      {
        "name": "df5ef8e4-1afe-43ac-8ea9-49f3c90ec93e",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Centro",
        "toTable": "dim Centro",
        "toColumn": "Id_Centro"
      },
      {
        "name": "df50c697-566b-4bb3-8553-57ec476742a3",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Clientes",
        "toTable": "dim Clientes",
        "toColumn": "Id_Clientes"
      },
      {
        "name": "f7910a5e-b2d3-451b-98ce-35eb306b4832",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Material",
        "toTable": "dim Material",
        "toColumn": "Id_Material"
      },
      {
        "name": "48611187-7263-4432-ba9b-1c90005657ba",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Organizacion_Ventas",
        "toTable": "dim Organizacion_Ventas",
        "toColumn": "Id_Organizacion_Ventas"
      },
      {
        "name": "9a783e47-5060-42c4-a0ac-c4d4a3e09896",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id Zona_Ventas",
        "toTable": "dim Zona_Ventas",
        "toColumn": "ID Geografia"
      },
      {
        "name": "30daceee-fbf0-4414-92a4-f78dff72eda1",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Sociedad",
        "toTable": "dim Sociedades",
        "toColumn": "Id_Sociedad"
      },
      {
        "name": "be962e84-1b76-4563-b6dd-1dbee59c73f9",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Sociedad",
        "toTable": "dim Sociedades",
        "toColumn": "Id_Sociedad"
      },
      {
        "name": "0df0edfa-a42f-41b0-ac4c-b44e1e8481d2",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Sectores",
        "toTable": "dim Sectores",
        "toColumn": "Id_Sectores"
      },
      {
        "name": "b3ef28bf-3e68-44d5-bc1c-1b3fae390655",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Sectores",
        "toTable": "dim Sectores",
        "toColumn": "Id_Sectores"
      },
      {
        "name": "932a1556-62a9-4bff-be45-dc1cc65a63e6",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Divisiones",
        "toTable": "dim Divisiones",
        "toColumn": "Id_Divisiones"
      },
      {
        "name": "d5346be6-d5dd-49df-9931-945a618ffe46",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Divisiones",
        "toTable": "dim Divisiones",
        "toColumn": "Id_Divisiones"
      },
      {
        "name": "d3bc6ba5-3eba-4c06-abcc-7762cc21ca1a",
        "fromTable": "Detalle Costes",
        "fromColumn": "Id",
        "toTable": "Metricas visuales Costes",
        "toColumn": "Id"
      },
      {
        "name": "42d40f49-868c-416b-95c3-ab4f49f352bb",
        "fromTable": "Detalle Costes 2",
        "fromColumn": "Id",
        "toTable": "Metricas visuales Costes",
        "toColumn": "Id"
      },
      {
        "name": "d0a13da8-649b-4284-b58a-9993458534fd",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Clientes",
        "toTable": "SeleccionClientes",
        "toColumn": "Id_Clientes"
      },
      {
        "name": "9f622d4d-e520-42c6-9fb0-53e460d3e985",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Clientes",
        "toTable": "SeleccionClientes",
        "toColumn": "Id_Clientes"
      },
      {
        "name": "1067da42-be6a-4574-8adf-c1348d19e35f",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Fecha",
        "toTable": "dim Fechas",
        "toColumn": "Fecha"
      },
      {
        "name": "d32c64b2-1ab4-4478-b7a6-0961a95cbe72",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Fecha",
        "toTable": "dim Fechas",
        "toColumn": "Fecha"
      },
      {
        "name": "980ae191-c9b6-4d61-b4d5-98ee565da7ef",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Ramo",
        "toTable": "Ramo_Industrial",
        "toColumn": "ID_Ramo"
      },
      {
        "name": "977dc51c-a678-4c30-8c89-bbc5c524e039",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Ramo",
        "toTable": "Ramo_Industrial",
        "toColumn": "ID_Ramo"
      },
      {
        "name": "0cfe8220-190c-4c84-94e4-9ce314ce4830",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Material",
        "toTable": "Materiales",
        "toColumn": "Id_Materiales",
        "isActive": false
      },
      {
        "name": "d04fdf7b-78a5-41ef-b9f8-1db17e5219ed",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Materiales",
        "toTable": "Materiales",
        "toColumn": "Id_Materiales",
        "isActive": false
      },
      {
        "name": "657d1f5d-2462-451f-ba4f-c933fff1f21d",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Atributos_Materiales_PROVISIONAL",
        "toTable": "dim Provisional_Atributos_Materiales_Costes",
        "toColumn": "Id_Atributos_Materiales_PROVISIONAL"
      },
      {
        "name": "6f07454a-2d3c-48d4-9553-910744748123",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Atributos_Materiales_PROVISIONAL",
        "toTable": "dim Provisional_Atributos_Materiales_Costes",
        "toColumn": "Id_Atributos_Materiales_PROVISIONAL"
      },
      {
        "name": "b62c7a07-4d8b-4325-8ef4-ecb68059b924",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Personal 1",
        "toTable": "dim Personal",
        "toColumn": "Id_Personal"
      },
      {
        "name": "223c7082-dcc1-4233-a9fe-a656f544b25a",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Personal 2",
        "toTable": "dim Personal",
        "toColumn": "Id_Personal",
        "isActive": false
      },
      {
        "name": "d100e673-c5c9-4eca-8472-ee983f4b0ee1",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Proveedor 1",
        "toTable": "dim Proveedores",
        "toColumn": "Id_Proveedores"
      },
      {
        "name": "b6fafa30-4ec2-4328-9fd9-6f49123864af",
        "fromTable": "fact Costes_Real",
        "fromColumn": "Id_Proveedor 2",
        "toTable": "dim Proveedores",
        "toColumn": "Id_Proveedores",
        "isActive": false
      },
      {
        "name": "28503094-5e29-42ed-a623-55a311ca7d0f",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Personal 1",
        "toTable": "dim Personal",
        "toColumn": "Id_Personal"
      },
      {
        "name": "99c5d10b-4d4b-48c1-8c70-ed3e7c2eb696",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Personal 2",
        "toTable": "dim Personal",
        "toColumn": "Id_Personal",
        "isActive": false
      },
      {
        "name": "6deaa47d-ad1e-4c55-8fa6-35e863c894e3",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Proveedor 1",
        "toTable": "dim Proveedores",
        "toColumn": "Id_Proveedores"
      },
      {
        "name": "f3e8857b-bde0-4c84-b146-07fcc694760d",
        "fromTable": "fact Costes_Plan",
        "fromColumn": "Id_Proveedor 2",
        "toTable": "dim Proveedores",
        "toColumn": "Id_Proveedores",
        "isActive": false
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}